/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZBuick extends javax.swing.JFrame {

    /**
     * Creates new form VenBuick
     */
    public ZBuick() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lesabreT = new javax.swing.JLabel();
        lesabreInfo1 = new javax.swing.JLabel();
        lesabreInfo2 = new javax.swing.JLabel();
        lesabreInfo3 = new javax.swing.JLabel();
        lesabreInfo4 = new javax.swing.JLabel();
        lesabreInfo5 = new javax.swing.JLabel();
        lesabreInfo6 = new javax.swing.JLabel();
        lesabreInfo7 = new javax.swing.JLabel();
        lesabreInfo8 = new javax.swing.JLabel();
        lesabreInfo9 = new javax.swing.JLabel();
        skylarkT = new javax.swing.JLabel();
        skylarkInfo1 = new javax.swing.JLabel();
        skylarkInfo2 = new javax.swing.JLabel();
        skylarkInfo3 = new javax.swing.JLabel();
        skylarkInfo4 = new javax.swing.JLabel();
        skylarkInfo5 = new javax.swing.JLabel();
        skylarkInfo6 = new javax.swing.JLabel();
        skylarkInfo7 = new javax.swing.JLabel();
        skylarkInfo8 = new javax.swing.JLabel();
        skylarkInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_proxima2 = new javax.swing.JButton();
        jtp_lesabre = new javax.swing.JTabbedPane();
        lesabre1 = new javax.swing.JLabel();
        lesabre2 = new javax.swing.JLabel();
        lesabre3 = new javax.swing.JLabel();
        jtp_skylark = new javax.swing.JTabbedPane();
        skylark1 = new javax.swing.JLabel();
        skylark2 = new javax.swing.JLabel();
        skylark3 = new javax.swing.JLabel();
        skylark4 = new javax.swing.JLabel();
        backBuick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buick 1/2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lesabreT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        lesabreT.setForeground(new java.awt.Color(255, 255, 255));
        lesabreT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lesabreT.setText("BUICK LeSabre 2D");
        getContentPane().add(lesabreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 310, 30));

        lesabreInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        lesabreInfo1.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(lesabreInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 310, 30));

        lesabreInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo2.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1970/1970"); // NOI18N
        getContentPane().add(lesabreInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        lesabreInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo3.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo3.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(lesabreInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 310, 30));

        lesabreInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo4.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo4.setText("MOTOR: 350 pol³ (5,7 litros) - V8"); // NOI18N
        getContentPane().add(lesabreInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 310, 30));

        lesabreInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo5.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo5.setText("POTÊNCIA: 264 CV"); // NOI18N
        getContentPane().add(lesabreInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 310, 30));

        lesabreInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo6.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo6.setText("VELOCIDADE MÁXIMA: 180 km/h"); // NOI18N
        getContentPane().add(lesabreInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 310, 30));

        lesabreInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo7.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(lesabreInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 310, 30));

        lesabreInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo8.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo8.setText("COR: Harvest Gold Metallic"); // NOI18N
        getContentPane().add(lesabreInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 310, 30));

        lesabreInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        lesabreInfo9.setForeground(new java.awt.Color(255, 255, 255));
        lesabreInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lesabreInfo9.setText("QUILOMETRAGEM: 97.850"); // NOI18N
        getContentPane().add(lesabreInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 310, 30));

        skylarkT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        skylarkT.setForeground(new java.awt.Color(255, 255, 255));
        skylarkT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skylarkT.setText("BUICK Skylark Convertible");
        getContentPane().add(skylarkT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 310, 30));

        skylarkInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        skylarkInfo1.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo1.setLabelFor(lesabreT);
        skylarkInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(skylarkInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 310, 30));

        skylarkInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo2.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo2.setLabelFor(lesabreT);
        skylarkInfo2.setText("ANO FABRICAÇÃO: 1964"); // NOI18N
        getContentPane().add(skylarkInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 310, 30));

        skylarkInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo3.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo3.setLabelFor(lesabreT);
        skylarkInfo3.setText("MOTOR: V8 - 340 cilindradas/5,6 litros"); // NOI18N
        getContentPane().add(skylarkInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 310, 30));

        skylarkInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo4.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo4.setLabelFor(lesabreT);
        skylarkInfo4.setText("POTÊNCIA: 299 CV"); // NOI18N
        getContentPane().add(skylarkInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 310, 30));

        skylarkInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo5.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo5.setLabelFor(lesabreT);
        skylarkInfo5.setText("QUILOMETRAGEM: 67.820"); // NOI18N
        getContentPane().add(skylarkInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 310, 30));

        skylarkInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo6.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo6.setLabelFor(lesabreT);
        skylarkInfo6.setText("TRANSMISSÃO: Automática, 2 GEN"); // NOI18N
        getContentPane().add(skylarkInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 310, 30));

        skylarkInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo7.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo7.setLabelFor(lesabreT);
        skylarkInfo7.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(skylarkInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 310, 30));

        skylarkInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo8.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo8.setLabelFor(lesabreT);
        skylarkInfo8.setText("COR: Vermelho"); // NOI18N
        getContentPane().add(skylarkInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 310, 30));

        skylarkInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        skylarkInfo9.setForeground(new java.awt.Color(255, 255, 255));
        skylarkInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        skylarkInfo9.setLabelFor(lesabreT);
        skylarkInfo9.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(skylarkInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 310, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima2.setText("Próxima");
        btn_proxima2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proxima2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 100, 30));

        jtp_lesabre.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_lesabre.setToolTipText("");
        jtp_lesabre.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        lesabre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/lesabre/LeSabre1.png"))); // NOI18N
        jtp_lesabre.addTab("1/3", lesabre1);

        lesabre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/lesabre/LeSabre2.png"))); // NOI18N
        jtp_lesabre.addTab("2/3", lesabre2);

        lesabre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/lesabre/LeSabre3.png"))); // NOI18N
        jtp_lesabre.addTab("3/3", lesabre3);

        getContentPane().add(jtp_lesabre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 350, 230));

        jtp_skylark.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_skylark.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        skylark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/skylark/Skylark1.png"))); // NOI18N
        jtp_skylark.addTab("1/4", skylark1);

        skylark2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/skylark/Skylark2.png"))); // NOI18N
        jtp_skylark.addTab("2/4", skylark2);

        skylark3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/skylark/Skylark3.png"))); // NOI18N
        jtp_skylark.addTab("3/4", skylark3);

        skylark4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/skylark/Skylark4.png"))); // NOI18N
        jtp_skylark.addTab("4/4", skylark4);

        getContentPane().add(jtp_skylark, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 350, 230));

        backBuick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backBuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZBuick.this.dispose();
        
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_proxima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proxima2ActionPerformed

        ZBuick2 b2 = new ZBuick2();
        b2.setVisible(true);
        
    }//GEN-LAST:event_btn_proxima2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBuick;
    private javax.swing.JButton btn_proxima2;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_lesabre;
    private javax.swing.JTabbedPane jtp_skylark;
    private javax.swing.JLabel lesabre1;
    private javax.swing.JLabel lesabre2;
    private javax.swing.JLabel lesabre3;
    private javax.swing.JLabel lesabreInfo1;
    private javax.swing.JLabel lesabreInfo2;
    private javax.swing.JLabel lesabreInfo3;
    private javax.swing.JLabel lesabreInfo4;
    private javax.swing.JLabel lesabreInfo5;
    private javax.swing.JLabel lesabreInfo6;
    private javax.swing.JLabel lesabreInfo7;
    private javax.swing.JLabel lesabreInfo8;
    private javax.swing.JLabel lesabreInfo9;
    private javax.swing.JLabel lesabreT;
    private javax.swing.JLabel skylark1;
    private javax.swing.JLabel skylark2;
    private javax.swing.JLabel skylark3;
    private javax.swing.JLabel skylark4;
    private javax.swing.JLabel skylarkInfo1;
    private javax.swing.JLabel skylarkInfo2;
    private javax.swing.JLabel skylarkInfo3;
    private javax.swing.JLabel skylarkInfo4;
    private javax.swing.JLabel skylarkInfo5;
    private javax.swing.JLabel skylarkInfo6;
    private javax.swing.JLabel skylarkInfo7;
    private javax.swing.JLabel skylarkInfo8;
    private javax.swing.JLabel skylarkInfo9;
    private javax.swing.JLabel skylarkT;
    // End of variables declaration//GEN-END:variables
}
