/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZBuick2 extends javax.swing.JFrame {

    /**
     * Creates new form VenBuick
     */
    public ZBuick2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rivieraT = new javax.swing.JLabel();
        rivieraInfo1 = new javax.swing.JLabel();
        rivieraInfo2 = new javax.swing.JLabel();
        rivieraInfo3 = new javax.swing.JLabel();
        rivieraInfo4 = new javax.swing.JLabel();
        rivieraInfo5 = new javax.swing.JLabel();
        rivieraInfo6 = new javax.swing.JLabel();
        rivieraInfo7 = new javax.swing.JLabel();
        rivieraInfo8 = new javax.swing.JLabel();
        rivieraInfo9 = new javax.swing.JLabel();
        wildcatT = new javax.swing.JLabel();
        wildcatInfo1 = new javax.swing.JLabel();
        wildcatInfo2 = new javax.swing.JLabel();
        wildcatInfo3 = new javax.swing.JLabel();
        wildcatInfo4 = new javax.swing.JLabel();
        wildcatInfo5 = new javax.swing.JLabel();
        wildcatInfo6 = new javax.swing.JLabel();
        wildcatInfo7 = new javax.swing.JLabel();
        wildcatInfo8 = new javax.swing.JLabel();
        wildcatInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        jtp_riviera = new javax.swing.JTabbedPane();
        riviera1 = new javax.swing.JLabel();
        riviera2 = new javax.swing.JLabel();
        riviera3 = new javax.swing.JLabel();
        jtp_wildcat = new javax.swing.JTabbedPane();
        wildcat1 = new javax.swing.JLabel();
        wildcat2 = new javax.swing.JLabel();
        wildcat3 = new javax.swing.JLabel();
        backBuick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buick 2/2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rivieraT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        rivieraT.setForeground(new java.awt.Color(255, 255, 255));
        rivieraT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rivieraT.setText("BUICK Riviera Stage-1");
        getContentPane().add(rivieraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 310, 30));

        rivieraInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        rivieraInfo1.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(rivieraInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 310, 30));

        rivieraInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo2.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo2.setText("ANO FABRICAÇÃO: 1973"); // NOI18N
        getContentPane().add(rivieraInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 310, 30));

        rivieraInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo3.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo3.setText("POTÊNCIA: 264 CV"); // NOI18N
        getContentPane().add(rivieraInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 310, 30));

        rivieraInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo4.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo4.setText("MOTOR: V8"); // NOI18N
        getContentPane().add(rivieraInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 310, 30));

        rivieraInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo5.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo5.setText("QUILOMETRAGEM: 83.200"); // NOI18N
        getContentPane().add(rivieraInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 310, 30));

        rivieraInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo6.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo6.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(rivieraInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 310, 30));

        rivieraInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo7.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(rivieraInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 310, 30));

        rivieraInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo8.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo8.setText("TRANSMISSÃO: Automática, 3 GEN"); // NOI18N
        getContentPane().add(rivieraInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 310, 30));

        rivieraInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        rivieraInfo9.setForeground(new java.awt.Color(255, 255, 255));
        rivieraInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rivieraInfo9.setText("COR: Marrom"); // NOI18N
        getContentPane().add(rivieraInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 310, 30));

        wildcatT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        wildcatT.setForeground(new java.awt.Color(255, 255, 255));
        wildcatT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wildcatT.setText("BUICK Wildcat");
        getContentPane().add(wildcatT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 310, 30));

        wildcatInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        wildcatInfo1.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(wildcatInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 310, 30));

        wildcatInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo2.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo2.setText("ANO FABRICAÇÃO: 1966"); // NOI18N
        getContentPane().add(wildcatInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 310, 30));

        wildcatInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo3.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo3.setText("POTÊNCIA: 330 CV"); // NOI18N
        getContentPane().add(wildcatInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 310, 30));

        wildcatInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo4.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo4.setText("MOTOR: V8"); // NOI18N
        getContentPane().add(wildcatInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 310, 30));

        wildcatInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo5.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo5.setText("COR: Branco"); // NOI18N
        getContentPane().add(wildcatInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 310, 30));

        wildcatInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo6.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo6.setText("TRANSMISSÃO: Automática"); // NOI18N
        getContentPane().add(wildcatInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 310, 30));

        wildcatInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo7.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(wildcatInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 310, 30));

        wildcatInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo8.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo8.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(wildcatInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 310, 30));

        wildcatInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        wildcatInfo9.setForeground(new java.awt.Color(255, 255, 255));
        wildcatInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wildcatInfo9.setText("QUILOMETRAGEM: 67.590"); // NOI18N
        getContentPane().add(wildcatInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 310, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_riviera.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_riviera.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        riviera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/riviera/Riviera1.png"))); // NOI18N
        jtp_riviera.addTab("1/3", riviera1);

        riviera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/riviera/Riviera2.png"))); // NOI18N
        jtp_riviera.addTab("2/3", riviera2);

        riviera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/riviera/Riviera3.png"))); // NOI18N
        jtp_riviera.addTab("3/3", riviera3);

        getContentPane().add(jtp_riviera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 350, 230));

        jtp_wildcat.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_wildcat.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        wildcat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/wildcat/Wildcat1.png"))); // NOI18N
        jtp_wildcat.addTab("1/3", wildcat1);

        wildcat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/wildcat/Wildcat2.png"))); // NOI18N
        jtp_wildcat.addTab("2/3", wildcat2);

        wildcat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/buick/wildcat/Wildcat3.png"))); // NOI18N
        jtp_wildcat.addTab("3/3", wildcat3);

        getContentPane().add(jtp_wildcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 350, 180));

        backBuick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backBuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZBuick2.this.dispose();
        
    }//GEN-LAST:event_btn_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    
  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBuick;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_riviera;
    private javax.swing.JTabbedPane jtp_wildcat;
    private javax.swing.JLabel riviera1;
    private javax.swing.JLabel riviera2;
    private javax.swing.JLabel riviera3;
    private javax.swing.JLabel rivieraInfo1;
    private javax.swing.JLabel rivieraInfo2;
    private javax.swing.JLabel rivieraInfo3;
    private javax.swing.JLabel rivieraInfo4;
    private javax.swing.JLabel rivieraInfo5;
    private javax.swing.JLabel rivieraInfo6;
    private javax.swing.JLabel rivieraInfo7;
    private javax.swing.JLabel rivieraInfo8;
    private javax.swing.JLabel rivieraInfo9;
    private javax.swing.JLabel rivieraT;
    private javax.swing.JLabel wildcat1;
    private javax.swing.JLabel wildcat2;
    private javax.swing.JLabel wildcat3;
    private javax.swing.JLabel wildcatInfo1;
    private javax.swing.JLabel wildcatInfo2;
    private javax.swing.JLabel wildcatInfo3;
    private javax.swing.JLabel wildcatInfo4;
    private javax.swing.JLabel wildcatInfo5;
    private javax.swing.JLabel wildcatInfo6;
    private javax.swing.JLabel wildcatInfo7;
    private javax.swing.JLabel wildcatInfo8;
    private javax.swing.JLabel wildcatInfo9;
    private javax.swing.JLabel wildcatT;
    // End of variables declaration//GEN-END:variables
}
