/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZChrysler3 extends javax.swing.JFrame {
    /**
     * Creates new form ZChrysler
     */
    public ZChrysler3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windsorT = new javax.swing.JLabel();
        windsorInfo1 = new javax.swing.JLabel();
        windsorInfo2 = new javax.swing.JLabel();
        windsorInfo3 = new javax.swing.JLabel();
        windsorInfo4 = new javax.swing.JLabel();
        windsorInfo5 = new javax.swing.JLabel();
        windsorInfo6 = new javax.swing.JLabel();
        windsorInfo7 = new javax.swing.JLabel();
        windsorInfo8 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        jtp_windsor = new javax.swing.JTabbedPane();
        windsor1 = new javax.swing.JLabel();
        windsor2 = new javax.swing.JLabel();
        windsor3 = new javax.swing.JLabel();
        windsor4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        backChrysler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chrysler 3/3");
        setMinimumSize(new java.awt.Dimension(1220, 800));
        setPreferredSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windsorT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        windsorT.setForeground(new java.awt.Color(255, 255, 255));
        windsorT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        windsorT.setText("CHRYSLER Windsor");
        getContentPane().add(windsorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 360, 30));

        windsorInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        windsorInfo1.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(windsorInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 360, 30));

        windsorInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo2.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo2.setText("ANO FABRICAÇÃO: 1960"); // NOI18N
        getContentPane().add(windsorInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 360, 30));

        windsorInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo3.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo3.setText("QUILOMETRAGEM: 42.020"); // NOI18N
        getContentPane().add(windsorInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 360, 30));

        windsorInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo4.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo4.setText("MOTOR: V8 (6,3 litros)"); // NOI18N
        getContentPane().add(windsorInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 360, 30));

        windsorInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo5.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo5.setText("POTÊNCIA: 305HP"); // NOI18N
        getContentPane().add(windsorInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 360, 30));

        windsorInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo6.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo6.setText("COR: Azul"); // NOI18N
        getContentPane().add(windsorInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 360, 30));

        windsorInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo7.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo7.setText("CÂMBIO: Automático"); // NOI18N
        getContentPane().add(windsorInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 360, 30));

        windsorInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        windsorInfo8.setForeground(new java.awt.Color(255, 255, 255));
        windsorInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        windsorInfo8.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(windsorInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 360, 30));
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 680, 180, -1));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 110, 30));

        jtp_windsor.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_windsor.setToolTipText("");
        jtp_windsor.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        windsor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/windsor/Windsor1.png"))); // NOI18N
        jtp_windsor.addTab("1/4", windsor1);

        windsor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/windsor/Windsor2.png"))); // NOI18N
        jtp_windsor.addTab("2/4", windsor2);

        windsor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/windsor/Windsor3.png"))); // NOI18N
        jtp_windsor.addTab("3/4", windsor3);

        windsor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/windsor/Windsor4.png"))); // NOI18N
        jtp_windsor.addTab("4/4", windsor4);

        getContentPane().add(jtp_windsor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 400, 240));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backChrysler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backChrysler, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        
        ZChrysler3.this.dispose();
        
    }//GEN-LAST:event_btn_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backChrysler;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JTabbedPane jtp_windsor;
    private javax.swing.JLabel windsor1;
    private javax.swing.JLabel windsor2;
    private javax.swing.JLabel windsor3;
    private javax.swing.JLabel windsor4;
    private javax.swing.JLabel windsorInfo1;
    private javax.swing.JLabel windsorInfo2;
    private javax.swing.JLabel windsorInfo3;
    private javax.swing.JLabel windsorInfo4;
    private javax.swing.JLabel windsorInfo5;
    private javax.swing.JLabel windsorInfo6;
    private javax.swing.JLabel windsorInfo7;
    private javax.swing.JLabel windsorInfo8;
    private javax.swing.JLabel windsorT;
    // End of variables declaration//GEN-END:variables
}
