/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZChrysler extends javax.swing.JFrame {

    /**
     * Creates new form ZChrysler
     */
    public ZChrysler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c300T = new javax.swing.JLabel();
        c300Info1 = new javax.swing.JLabel();
        c300Info2 = new javax.swing.JLabel();
        c300Info3 = new javax.swing.JLabel();
        c300Info4 = new javax.swing.JLabel();
        c300Info5 = new javax.swing.JLabel();
        c300Info6 = new javax.swing.JLabel();
        c300Info7 = new javax.swing.JLabel();
        c300Info8 = new javax.swing.JLabel();
        c300Info9 = new javax.swing.JLabel();
        crownT = new javax.swing.JLabel();
        crownInfo1 = new javax.swing.JLabel();
        crownInfo2 = new javax.swing.JLabel();
        crownInfo3 = new javax.swing.JLabel();
        crownInfo4 = new javax.swing.JLabel();
        crownInfo5 = new javax.swing.JLabel();
        crownInfo6 = new javax.swing.JLabel();
        crownInfo7 = new javax.swing.JLabel();
        crownInfo8 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_300 = new javax.swing.JTabbedPane();
        c3001 = new javax.swing.JLabel();
        c3002 = new javax.swing.JLabel();
        c3003 = new javax.swing.JLabel();
        c3004 = new javax.swing.JLabel();
        jtp_crown = new javax.swing.JTabbedPane();
        crown1 = new javax.swing.JLabel();
        crown2 = new javax.swing.JLabel();
        crown3 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        backChrysler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chrysler 1/3");
        setMinimumSize(new java.awt.Dimension(1220, 800));
        setPreferredSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c300T.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        c300T.setForeground(new java.awt.Color(255, 255, 255));
        c300T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c300T.setText("CHRYSLER 300");
        getContentPane().add(c300T, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        c300Info1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        c300Info1.setForeground(new java.awt.Color(255, 255, 255));
        c300Info1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(c300Info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        c300Info2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info2.setForeground(new java.awt.Color(255, 255, 255));
        c300Info2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info2.setText("ANO FABRICAÇÃO/ANO MODELO: 1970/1970"); // NOI18N
        getContentPane().add(c300Info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        c300Info3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info3.setForeground(new java.awt.Color(255, 255, 255));
        c300Info3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info3.setText("COR: Marrom"); // NOI18N
        getContentPane().add(c300Info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        c300Info4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info4.setForeground(new java.awt.Color(255, 255, 255));
        c300Info4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info4.setText("CÂMBIO: Automático - 3 Velocidades"); // NOI18N
        getContentPane().add(c300Info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        c300Info5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info5.setForeground(new java.awt.Color(255, 255, 255));
        c300Info5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info5.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(c300Info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        c300Info6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info6.setForeground(new java.awt.Color(255, 255, 255));
        c300Info6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info6.setText("VELOCIDADE MÁXIMA: 207 km/h"); // NOI18N
        getContentPane().add(c300Info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        c300Info7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info7.setForeground(new java.awt.Color(255, 255, 255));
        c300Info7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info7.setText("POTÊNCIA: 375HP"); // NOI18N
        getContentPane().add(c300Info7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        c300Info8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info8.setForeground(new java.awt.Color(255, 255, 255));
        c300Info8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info8.setText("MOTOR: 440 pol³"); // NOI18N
        getContentPane().add(c300Info8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        c300Info9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300Info9.setForeground(new java.awt.Color(255, 255, 255));
        c300Info9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300Info9.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(c300Info9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        crownT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        crownT.setForeground(new java.awt.Color(255, 255, 255));
        crownT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crownT.setText("CHRYSLER Crown Imperial");
        getContentPane().add(crownT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        crownInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        crownInfo1.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(crownInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        crownInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo2.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo2.setText("ANO FABRICAÇÃO: 1948"); // NOI18N
        getContentPane().add(crownInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        crownInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo3.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo3.setText("COR: Preto"); // NOI18N
        getContentPane().add(crownInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        crownInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo4.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo4.setText("POTÊNCIA: 137HP"); // NOI18N
        getContentPane().add(crownInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        crownInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo5.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo5.setText("CÂMBIO: Manual"); // NOI18N
        getContentPane().add(crownInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        crownInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo6.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo6.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(crownInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        crownInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo7.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo7.setText("MOTOR: V8 (5,4 litros)"); // NOI18N
        getContentPane().add(crownInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        crownInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        crownInfo8.setForeground(new java.awt.Color(255, 255, 255));
        crownInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crownInfo8.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(crownInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 680, 180, -1));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_300.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_300.setToolTipText("");
        jtp_300.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        c3001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300/300-1.png"))); // NOI18N
        jtp_300.addTab("1/4", c3001);

        c3002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300/300-2.png"))); // NOI18N
        jtp_300.addTab("2/4", c3002);

        c3003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300/300-3.png"))); // NOI18N
        jtp_300.addTab("3/4", c3003);

        c3004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300/300-4.png"))); // NOI18N
        jtp_300.addTab("4/4", c3004);

        getContentPane().add(jtp_300, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_crown.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_crown.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        crown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/crown/Crown1.png"))); // NOI18N
        jtp_crown.addTab("1/3", crown1);

        crown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/crown/Crown2.png"))); // NOI18N
        jtp_crown.addTab("2/3", crown2);

        crown3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/crown/Crown3.png"))); // NOI18N
        jtp_crown.addTab("3/3", crown3);

        getContentPane().add(jtp_crown, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 370, 230));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backChrysler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backChrysler, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed
        
        ZChrysler2 c2 = new ZChrysler2();
        c2.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZChrysler.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backChrysler;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel c3001;
    private javax.swing.JLabel c3002;
    private javax.swing.JLabel c3003;
    private javax.swing.JLabel c3004;
    private javax.swing.JLabel c300Info1;
    private javax.swing.JLabel c300Info2;
    private javax.swing.JLabel c300Info3;
    private javax.swing.JLabel c300Info4;
    private javax.swing.JLabel c300Info5;
    private javax.swing.JLabel c300Info6;
    private javax.swing.JLabel c300Info7;
    private javax.swing.JLabel c300Info8;
    private javax.swing.JLabel c300Info9;
    private javax.swing.JLabel c300T;
    private javax.swing.JLabel crown1;
    private javax.swing.JLabel crown2;
    private javax.swing.JLabel crown3;
    private javax.swing.JLabel crownInfo1;
    private javax.swing.JLabel crownInfo2;
    private javax.swing.JLabel crownInfo3;
    private javax.swing.JLabel crownInfo4;
    private javax.swing.JLabel crownInfo5;
    private javax.swing.JLabel crownInfo6;
    private javax.swing.JLabel crownInfo7;
    private javax.swing.JLabel crownInfo8;
    private javax.swing.JLabel crownT;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JTabbedPane jtp_300;
    private javax.swing.JTabbedPane jtp_crown;
    // End of variables declaration//GEN-END:variables
}
