/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZChrysler2 extends javax.swing.JFrame {

    /**
     * Creates new form ZChrysler
     */
    public ZChrysler2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c300kT = new javax.swing.JLabel();
        c300kInfo1 = new javax.swing.JLabel();
        c300kInfo2 = new javax.swing.JLabel();
        c300kInfo3 = new javax.swing.JLabel();
        c300kInfo4 = new javax.swing.JLabel();
        c300kInfo5 = new javax.swing.JLabel();
        c300kInfo6 = new javax.swing.JLabel();
        c300kInfo7 = new javax.swing.JLabel();
        c300kInfo8 = new javax.swing.JLabel();
        c300kInfo9 = new javax.swing.JLabel();
        stratusT = new javax.swing.JLabel();
        stratusInfo1 = new javax.swing.JLabel();
        stratusInfo2 = new javax.swing.JLabel();
        stratusInfo3 = new javax.swing.JLabel();
        stratusInfo4 = new javax.swing.JLabel();
        stratusInfo5 = new javax.swing.JLabel();
        stratusInfo6 = new javax.swing.JLabel();
        stratusInfo7 = new javax.swing.JLabel();
        stratusInfo8 = new javax.swing.JLabel();
        stratusInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_300k = new javax.swing.JTabbedPane();
        c300k1 = new javax.swing.JLabel();
        c300k2 = new javax.swing.JLabel();
        c300k3 = new javax.swing.JLabel();
        c300k4 = new javax.swing.JLabel();
        jtp_stratus = new javax.swing.JTabbedPane();
        stratus1 = new javax.swing.JLabel();
        stratus2 = new javax.swing.JLabel();
        stratus3 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        backChrysler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chrysler 2/3");
        setMinimumSize(new java.awt.Dimension(1220, 800));
        setPreferredSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c300kT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        c300kT.setForeground(new java.awt.Color(255, 255, 255));
        c300kT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c300kT.setText("CHRYSLER 300 K");
        getContentPane().add(c300kT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        c300kInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        c300kInfo1.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(c300kInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        c300kInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo2.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo2.setText("ANO FABRICAÇÃO: 1964"); // NOI18N
        getContentPane().add(c300kInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        c300kInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo3.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo3.setText("QUILOMETRAGEM: 24.680"); // NOI18N
        getContentPane().add(c300kInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        c300kInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo4.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo4.setText("POTÊNCIA: 340HP"); // NOI18N
        getContentPane().add(c300kInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        c300kInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo5.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo5.setText("MOTOR: V8"); // NOI18N
        getContentPane().add(c300kInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        c300kInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo6.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo6.setText("CÂMBIO: Automático - 3 Velocidades"); // NOI18N
        getContentPane().add(c300kInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        c300kInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo7.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(c300kInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        c300kInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo8.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo8.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(c300kInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        c300kInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        c300kInfo9.setForeground(new java.awt.Color(255, 255, 255));
        c300kInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        c300kInfo9.setText("COR: Branco"); // NOI18N
        getContentPane().add(c300kInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        stratusT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        stratusT.setForeground(new java.awt.Color(255, 255, 255));
        stratusT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stratusT.setText("CHRYSLER Stratus LX Conversível");
        getContentPane().add(stratusT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        stratusInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        stratusInfo1.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(stratusInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        stratusInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo2.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1997/1998"); // NOI18N
        getContentPane().add(stratusInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        stratusInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo3.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo3.setText("COR: Roxo"); // NOI18N
        getContentPane().add(stratusInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        stratusInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo4.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo4.setText("QUILOMETRAGEM: 71.400"); // NOI18N
        getContentPane().add(stratusInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        stratusInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo5.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo5.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(stratusInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        stratusInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo6.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo6.setText("MOTOR: 2.5"); // NOI18N
        getContentPane().add(stratusInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        stratusInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo7.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo7.setText("POTÊNCIA: 161CV"); // NOI18N
        getContentPane().add(stratusInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        stratusInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo8.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo8.setText("CÂMBIO: Automático - 4 Velocidades"); // NOI18N
        getContentPane().add(stratusInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));

        stratusInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        stratusInfo9.setForeground(new java.awt.Color(255, 255, 255));
        stratusInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stratusInfo9.setText("TRAÇÃO: Dianteira"); // NOI18N
        getContentPane().add(stratusInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 330, 30));
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 680, 180, -1));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Anterior");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_300k.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_300k.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        c300k1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300k/300k-1.png"))); // NOI18N
        jtp_300k.addTab("1/4", c300k1);

        c300k2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300k/300k-2.png"))); // NOI18N
        jtp_300k.addTab("2/4", c300k2);

        c300k3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300k/300k-3.png"))); // NOI18N
        jtp_300k.addTab("3/4", c300k3);

        c300k4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/300k/300k-4.png"))); // NOI18N
        jtp_300k.addTab("4/4", c300k4);

        getContentPane().add(jtp_300k, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 380, 220));

        jtp_stratus.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_stratus.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        stratus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/stratus/Stratus1.png"))); // NOI18N
        jtp_stratus.addTab("1/3", stratus1);

        stratus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/stratus/Stratus2.png"))); // NOI18N
        jtp_stratus.addTab("2/3", stratus2);

        stratus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/chrysler/stratus/Stratus3.png"))); // NOI18N
        jtp_stratus.addTab("3/3", stratus3);

        getContentPane().add(jtp_stratus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 370, 220));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backChrysler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backChrysler, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed
        
        ZChrysler3 c3 = new ZChrysler3();
        c3.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZChrysler2.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backChrysler;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel c300k1;
    private javax.swing.JLabel c300k2;
    private javax.swing.JLabel c300k3;
    private javax.swing.JLabel c300k4;
    private javax.swing.JLabel c300kInfo1;
    private javax.swing.JLabel c300kInfo2;
    private javax.swing.JLabel c300kInfo3;
    private javax.swing.JLabel c300kInfo4;
    private javax.swing.JLabel c300kInfo5;
    private javax.swing.JLabel c300kInfo6;
    private javax.swing.JLabel c300kInfo7;
    private javax.swing.JLabel c300kInfo8;
    private javax.swing.JLabel c300kInfo9;
    private javax.swing.JLabel c300kT;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JTabbedPane jtp_300k;
    private javax.swing.JTabbedPane jtp_stratus;
    private javax.swing.JLabel stratus1;
    private javax.swing.JLabel stratus2;
    private javax.swing.JLabel stratus3;
    private javax.swing.JLabel stratusInfo1;
    private javax.swing.JLabel stratusInfo2;
    private javax.swing.JLabel stratusInfo3;
    private javax.swing.JLabel stratusInfo4;
    private javax.swing.JLabel stratusInfo5;
    private javax.swing.JLabel stratusInfo6;
    private javax.swing.JLabel stratusInfo7;
    private javax.swing.JLabel stratusInfo8;
    private javax.swing.JLabel stratusInfo9;
    private javax.swing.JLabel stratusT;
    // End of variables declaration//GEN-END:variables
}
