/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZDodge2 extends javax.swing.JFrame {

    /**
     * Creates new form ZDodge
     */
    public ZDodge2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ramT = new javax.swing.JLabel();
        ramInfo1 = new javax.swing.JLabel();
        ramInfo2 = new javax.swing.JLabel();
        ramInfo3 = new javax.swing.JLabel();
        ramInfo4 = new javax.swing.JLabel();
        ramInfo5 = new javax.swing.JLabel();
        ramInfo6 = new javax.swing.JLabel();
        ramInfo7 = new javax.swing.JLabel();
        ramInfo8 = new javax.swing.JLabel();
        ramInfo9 = new javax.swing.JLabel();
        dartT = new javax.swing.JLabel();
        dartInfo1 = new javax.swing.JLabel();
        dartInfo2 = new javax.swing.JLabel();
        dartInfo3 = new javax.swing.JLabel();
        dartInfo4 = new javax.swing.JLabel();
        dartInfo5 = new javax.swing.JLabel();
        dartInfo6 = new javax.swing.JLabel();
        dartInfo7 = new javax.swing.JLabel();
        dartInfo8 = new javax.swing.JLabel();
        dartInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        btn_proxima = new javax.swing.JButton();
        jtp_ram = new javax.swing.JTabbedPane();
        ram1 = new javax.swing.JLabel();
        ram2 = new javax.swing.JLabel();
        ram3 = new javax.swing.JLabel();
        ram4 = new javax.swing.JLabel();
        jtp_dart = new javax.swing.JTabbedPane();
        dart1 = new javax.swing.JLabel();
        dart2 = new javax.swing.JLabel();
        dart3 = new javax.swing.JLabel();
        dart4 = new javax.swing.JLabel();
        backDodge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodge 2/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ramT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        ramT.setForeground(new java.awt.Color(255, 255, 255));
        ramT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ramT.setText("DODGE Ram 1500 5.2 V8");
        getContentPane().add(ramT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        ramInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        ramInfo1.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(ramInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        ramInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo2.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1995/1995 "); // NOI18N
        getContentPane().add(ramInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        ramInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo3.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo3.setText("COR: Branco"); // NOI18N
        getContentPane().add(ramInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        ramInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo4.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo4.setText("QUILOMETRAGEM: 64.967 milhas"); // NOI18N
        getContentPane().add(ramInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        ramInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo5.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo5.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(ramInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        ramInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo6.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo6.setText("MOTOR: Magnum V8 (5.2 litros)"); // NOI18N
        getContentPane().add(ramInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        ramInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo7.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo7.setText("POTÊNCIA: 230 CV"); // NOI18N
        getContentPane().add(ramInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        ramInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo8.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo8.setText("CÂMBIO: Automático - 4 velocidades"); // NOI18N
        getContentPane().add(ramInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        ramInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        ramInfo9.setForeground(new java.awt.Color(255, 255, 255));
        ramInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ramInfo9.setText("TRAÇÃO: Integral temporária"); // NOI18N
        getContentPane().add(ramInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        dartT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        dartT.setForeground(new java.awt.Color(255, 255, 255));
        dartT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dartT.setText("DODGE Dart V8");
        getContentPane().add(dartT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 340, 30));

        dartInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        dartInfo1.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(dartInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 340, 30));

        dartInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo2.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1974/1974"); // NOI18N
        getContentPane().add(dartInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 340, 30));

        dartInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo3.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo3.setText("COR: Laranja"); // NOI18N
        getContentPane().add(dartInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 340, 30));

        dartInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo4.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo4.setText("QUILOMETRAGEM: 464"); // NOI18N
        getContentPane().add(dartInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 340, 30));

        dartInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo5.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo5.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(dartInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 340, 30));

        dartInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo6.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo6.setText("MOTOR: 318pol³ V8"); // NOI18N
        getContentPane().add(dartInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 340, 30));

        dartInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo7.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo7.setText("POTÊNCIA: 285 CV"); // NOI18N
        getContentPane().add(dartInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 340, 30));

        dartInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo8.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo8.setText("CÂMBIO: Manual - 4 velocidades"); // NOI18N
        getContentPane().add(dartInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 340, 30));

        dartInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dartInfo9.setForeground(new java.awt.Color(255, 255, 255));
        dartInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dartInfo9.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(dartInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 340, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        jtp_ram.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_ram.setToolTipText("");
        jtp_ram.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        ram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/ram/Ram.png"))); // NOI18N
        jtp_ram.addTab("1/4", ram1);

        ram2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/ram/Ram1.png"))); // NOI18N
        jtp_ram.addTab("2/4", ram2);

        ram3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/ram/Ram2.png"))); // NOI18N
        jtp_ram.addTab("3/4", ram3);

        ram4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/ram/Ram3.png"))); // NOI18N
        jtp_ram.addTab("4/4", ram4);

        getContentPane().add(jtp_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_dart.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_dart.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        dart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/dart/Dart1.png"))); // NOI18N
        jtp_dart.addTab("1/4", dart1);

        dart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/dart/Dart2.png"))); // NOI18N
        jtp_dart.addTab("2/4", dart2);

        dart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/dart/Dart3.png"))); // NOI18N
        jtp_dart.addTab("3/4", dart3);

        dart4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/dart/Dart4.png"))); // NOI18N
        jtp_dart.addTab("4/4", dart4);

        getContentPane().add(jtp_dart, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 380, 220));

        backDodge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backDodge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZDodge2.this.dispose();

    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZDodge3 d3 = new ZDodge3();
        d3.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backDodge;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JLabel dart1;
    private javax.swing.JLabel dart2;
    private javax.swing.JLabel dart3;
    private javax.swing.JLabel dart4;
    private javax.swing.JLabel dartInfo1;
    private javax.swing.JLabel dartInfo2;
    private javax.swing.JLabel dartInfo3;
    private javax.swing.JLabel dartInfo4;
    private javax.swing.JLabel dartInfo5;
    private javax.swing.JLabel dartInfo6;
    private javax.swing.JLabel dartInfo7;
    private javax.swing.JLabel dartInfo8;
    private javax.swing.JLabel dartInfo9;
    private javax.swing.JLabel dartT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_dart;
    private javax.swing.JTabbedPane jtp_ram;
    private javax.swing.JLabel ram1;
    private javax.swing.JLabel ram2;
    private javax.swing.JLabel ram3;
    private javax.swing.JLabel ram4;
    private javax.swing.JLabel ramInfo1;
    private javax.swing.JLabel ramInfo2;
    private javax.swing.JLabel ramInfo3;
    private javax.swing.JLabel ramInfo4;
    private javax.swing.JLabel ramInfo5;
    private javax.swing.JLabel ramInfo6;
    private javax.swing.JLabel ramInfo7;
    private javax.swing.JLabel ramInfo8;
    private javax.swing.JLabel ramInfo9;
    private javax.swing.JLabel ramT;
    // End of variables declaration//GEN-END:variables
}
