/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZDodge3 extends javax.swing.JFrame {

    /**
     * Creates new form ZDodge
     */
    public ZDodge3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        magnumT = new javax.swing.JLabel();
        magnumInfo1 = new javax.swing.JLabel();
        magnumInfo2 = new javax.swing.JLabel();
        magnumInfo3 = new javax.swing.JLabel();
        magnumInfo4 = new javax.swing.JLabel();
        magnumInfo5 = new javax.swing.JLabel();
        magnumInfo6 = new javax.swing.JLabel();
        magnumInfo7 = new javax.swing.JLabel();
        magnumInfo8 = new javax.swing.JLabel();
        magnumInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        jtp_magnum = new javax.swing.JTabbedPane();
        magnum1 = new javax.swing.JLabel();
        magnum2 = new javax.swing.JLabel();
        magnum3 = new javax.swing.JLabel();
        backDodge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodge 3/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        magnumT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        magnumT.setForeground(new java.awt.Color(255, 255, 255));
        magnumT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magnumT.setText("DODGE Magnum");
        getContentPane().add(magnumT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 330, 30));

        magnumInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        magnumInfo1.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(magnumInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 330, 30));

        magnumInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo2.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1979/1979"); // NOI18N
        getContentPane().add(magnumInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 330, 30));

        magnumInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo3.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo3.setText("COR: Azul Cadete"); // NOI18N
        getContentPane().add(magnumInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 330, 30));

        magnumInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo4.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo4.setText("QUILOMETRAGEM: 88.000"); // NOI18N
        getContentPane().add(magnumInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 330, 30));

        magnumInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo5.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo5.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(magnumInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 330, 30));

        magnumInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo6.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo6.setText("MOTOR: V8 (5.2 litros)"); // NOI18N
        getContentPane().add(magnumInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 330, 30));

        magnumInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo7.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo7.setText("POTÊNCIA: 208CV"); // NOI18N
        getContentPane().add(magnumInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 330, 30));

        magnumInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo8.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo8.setText("CÂMBIO: Manual - 4 Velocidades"); // NOI18N
        getContentPane().add(magnumInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 330, 30));

        magnumInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        magnumInfo9.setForeground(new java.awt.Color(255, 255, 255));
        magnumInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        magnumInfo9.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(magnumInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 330, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_magnum.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_magnum.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        magnum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/magnum/Magnum1.png"))); // NOI18N
        jtp_magnum.addTab("1/3", magnum1);

        magnum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/magnum/Magnum2.png"))); // NOI18N
        jtp_magnum.addTab("2/3", magnum2);

        magnum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/magnum/Magnum3.png"))); // NOI18N
        jtp_magnum.addTab("3/3", magnum3);

        getContentPane().add(jtp_magnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 370, 220));

        backDodge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backDodge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZDodge3.this.dispose();

    }//GEN-LAST:event_btn_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backDodge;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_magnum;
    private javax.swing.JLabel magnum1;
    private javax.swing.JLabel magnum2;
    private javax.swing.JLabel magnum3;
    private javax.swing.JLabel magnumInfo1;
    private javax.swing.JLabel magnumInfo2;
    private javax.swing.JLabel magnumInfo3;
    private javax.swing.JLabel magnumInfo4;
    private javax.swing.JLabel magnumInfo5;
    private javax.swing.JLabel magnumInfo6;
    private javax.swing.JLabel magnumInfo7;
    private javax.swing.JLabel magnumInfo8;
    private javax.swing.JLabel magnumInfo9;
    private javax.swing.JLabel magnumT;
    // End of variables declaration//GEN-END:variables
}
