/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZDodge extends javax.swing.JFrame {

    /**
     * Creates new form ZDodge
     */
    public ZDodge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        challengerT = new javax.swing.JLabel();
        challengerInfo1 = new javax.swing.JLabel();
        challengerInfo2 = new javax.swing.JLabel();
        challengerInfo3 = new javax.swing.JLabel();
        challengerInfo4 = new javax.swing.JLabel();
        challengerInfo5 = new javax.swing.JLabel();
        challengerInfo6 = new javax.swing.JLabel();
        challengerInfo7 = new javax.swing.JLabel();
        challengerInfo8 = new javax.swing.JLabel();
        challengerInfo9 = new javax.swing.JLabel();
        chargerT = new javax.swing.JLabel();
        chargerInfo1 = new javax.swing.JLabel();
        chargerInfo2 = new javax.swing.JLabel();
        chargerInfo3 = new javax.swing.JLabel();
        chargerInfo4 = new javax.swing.JLabel();
        chargerInfo5 = new javax.swing.JLabel();
        chargerInfo6 = new javax.swing.JLabel();
        chargerInfo7 = new javax.swing.JLabel();
        chargerInfo8 = new javax.swing.JLabel();
        chargerInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_challenger = new javax.swing.JTabbedPane();
        challenger1 = new javax.swing.JLabel();
        challenger2 = new javax.swing.JLabel();
        challenger3 = new javax.swing.JLabel();
        challenger4 = new javax.swing.JLabel();
        jtp_charger = new javax.swing.JTabbedPane();
        charger1 = new javax.swing.JLabel();
        charger2 = new javax.swing.JLabel();
        charger3 = new javax.swing.JLabel();
        backDodge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodge 1/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        challengerT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        challengerT.setForeground(new java.awt.Color(255, 255, 255));
        challengerT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        challengerT.setText("DODGE Challenger R/T 440 Six-Pack");
        getContentPane().add(challengerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        challengerInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        challengerInfo1.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(challengerInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        challengerInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo2.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1971/1971"); // NOI18N
        getContentPane().add(challengerInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        challengerInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo3.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo3.setText("VELOCIDADE MÁXIMA: 228 Km/h"); // NOI18N
        getContentPane().add(challengerInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        challengerInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo4.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo4.setText("CÂMBIO: Manual - 5 Velocidades"); // NOI18N
        getContentPane().add(challengerInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        challengerInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo5.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo5.setText("MOTOR: 440 pol³"); // NOI18N
        getContentPane().add(challengerInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        challengerInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo6.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo6.setText("POTÊNCIA: 450 CV"); // NOI18N
        getContentPane().add(challengerInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        challengerInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo7.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo7.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(challengerInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        challengerInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo8.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo8.setText("COR: Bright Blue Metallic"); // NOI18N
        getContentPane().add(challengerInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        challengerInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        challengerInfo9.setForeground(new java.awt.Color(255, 255, 255));
        challengerInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        challengerInfo9.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(challengerInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        chargerT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        chargerT.setForeground(new java.awt.Color(255, 255, 255));
        chargerT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chargerT.setText("DODGE Charger");
        getContentPane().add(chargerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        chargerInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        chargerInfo1.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(chargerInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        chargerInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo2.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1972/1972"); // NOI18N
        getContentPane().add(chargerInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        chargerInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo3.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo3.setText("COR: Ouro Espanhol"); // NOI18N
        getContentPane().add(chargerInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        chargerInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo4.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo4.setText("QUILOMETRAGEM: 98.800"); // NOI18N
        getContentPane().add(chargerInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        chargerInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo5.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo5.setText("COMBUSTÍVEL: Gasolina"); // NOI18N
        getContentPane().add(chargerInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        chargerInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo6.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo6.setText("MOTOR: V8 (5.2 litros)"); // NOI18N
        getContentPane().add(chargerInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        chargerInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo7.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo7.setText("POTÊNCIA: 208CV"); // NOI18N
        getContentPane().add(chargerInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        chargerInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo8.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo8.setText("CÂMBIO: Manual - 4 Velocidades"); // NOI18N
        getContentPane().add(chargerInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));

        chargerInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        chargerInfo9.setForeground(new java.awt.Color(255, 255, 255));
        chargerInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargerInfo9.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(chargerInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 330, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_challenger.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_challenger.setToolTipText("");
        jtp_challenger.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        challenger1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/challenger/Challenger1.png"))); // NOI18N
        jtp_challenger.addTab("1/4", challenger1);

        challenger2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/challenger/Challenger2.png"))); // NOI18N
        jtp_challenger.addTab("2/4", challenger2);

        challenger3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/challenger/Challenger3.png"))); // NOI18N
        jtp_challenger.addTab("3/4", challenger3);

        challenger4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/challenger/Challenger4.png"))); // NOI18N
        jtp_challenger.addTab("4/4", challenger4);

        getContentPane().add(jtp_challenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_charger.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_charger.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        charger1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/charger/Charger1.png"))); // NOI18N
        jtp_charger.addTab("1/3", charger1);

        charger2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/charger/Charger2.png"))); // NOI18N
        jtp_charger.addTab("2/3", charger2);

        charger3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/dodge/charger/Charger3.png"))); // NOI18N
        jtp_charger.addTab("3/3", charger3);

        getContentPane().add(jtp_charger, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 370, 230));

        backDodge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backDodge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZDodge2 d2 = new ZDodge2();
        d2.setVisible(true);

    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZDodge.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backDodge;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel challenger1;
    private javax.swing.JLabel challenger2;
    private javax.swing.JLabel challenger3;
    private javax.swing.JLabel challenger4;
    private javax.swing.JLabel challengerInfo1;
    private javax.swing.JLabel challengerInfo2;
    private javax.swing.JLabel challengerInfo3;
    private javax.swing.JLabel challengerInfo4;
    private javax.swing.JLabel challengerInfo5;
    private javax.swing.JLabel challengerInfo6;
    private javax.swing.JLabel challengerInfo7;
    private javax.swing.JLabel challengerInfo8;
    private javax.swing.JLabel challengerInfo9;
    private javax.swing.JLabel challengerT;
    private javax.swing.JLabel charger1;
    private javax.swing.JLabel charger2;
    private javax.swing.JLabel charger3;
    private javax.swing.JLabel chargerInfo1;
    private javax.swing.JLabel chargerInfo2;
    private javax.swing.JLabel chargerInfo3;
    private javax.swing.JLabel chargerInfo4;
    private javax.swing.JLabel chargerInfo5;
    private javax.swing.JLabel chargerInfo6;
    private javax.swing.JLabel chargerInfo7;
    private javax.swing.JLabel chargerInfo8;
    private javax.swing.JLabel chargerInfo9;
    private javax.swing.JLabel chargerT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_challenger;
    private javax.swing.JTabbedPane jtp_charger;
    // End of variables declaration//GEN-END:variables
}
