/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZFord3 extends javax.swing.JFrame {

    /**
     * Creates new form ZFord
     */
    public ZFord3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1T = new javax.swing.JLabel();
        f1Info1 = new javax.swing.JLabel();
        f1Info2 = new javax.swing.JLabel();
        f1Info3 = new javax.swing.JLabel();
        f1Info4 = new javax.swing.JLabel();
        f1Info5 = new javax.swing.JLabel();
        f1Info6 = new javax.swing.JLabel();
        f1Info7 = new javax.swing.JLabel();
        f1Info8 = new javax.swing.JLabel();
        f1Info9 = new javax.swing.JLabel();
        hotrodT = new javax.swing.JLabel();
        hotrodInfo1 = new javax.swing.JLabel();
        hotrodInfo2 = new javax.swing.JLabel();
        hotrodInfo3 = new javax.swing.JLabel();
        hotrodInfo4 = new javax.swing.JLabel();
        hotrodInfo5 = new javax.swing.JLabel();
        hotrodInfo6 = new javax.swing.JLabel();
        hotrodInfo7 = new javax.swing.JLabel();
        hotrodInfo8 = new javax.swing.JLabel();
        hotrodInfo9 = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        jtp_f1 = new javax.swing.JTabbedPane();
        f11 = new javax.swing.JLabel();
        f12 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        f14 = new javax.swing.JLabel();
        jtp_hotrod = new javax.swing.JTabbedPane();
        hotrod1 = new javax.swing.JLabel();
        hotrod2 = new javax.swing.JLabel();
        hotrod3 = new javax.swing.JLabel();
        hotrod4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        backFord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ford 3/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f1T.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        f1T.setForeground(new java.awt.Color(255, 255, 255));
        f1T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1T.setText("FORD F1 Pick Up");
        getContentPane().add(f1T, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        f1Info1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        f1Info1.setForeground(new java.awt.Color(255, 255, 255));
        f1Info1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(f1Info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        f1Info2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info2.setForeground(new java.awt.Color(255, 255, 255));
        f1Info2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info2.setText("POTÊNCIA: 101 CV"); // NOI18N
        getContentPane().add(f1Info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        f1Info3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info3.setForeground(new java.awt.Color(255, 255, 255));
        f1Info3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info3.setText("MOTOR: 3.9 V8"); // NOI18N
        getContentPane().add(f1Info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        f1Info4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info4.setForeground(new java.awt.Color(255, 255, 255));
        f1Info4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info4.setText("ANO FABRICAÇÃO/ANO MODELO: 1951/1951"); // NOI18N
        getContentPane().add(f1Info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        f1Info5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info5.setForeground(new java.awt.Color(255, 255, 255));
        f1Info5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info5.setText("COR: Vermelho (Vermilion)"); // NOI18N
        getContentPane().add(f1Info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        f1Info6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info6.setForeground(new java.awt.Color(255, 255, 255));
        f1Info6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info6.setText("PORTAS: 2"); // NOI18N
        getContentPane().add(f1Info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        f1Info7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info7.setForeground(new java.awt.Color(255, 255, 255));
        f1Info7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info7.setText("CÂMBIO: Manual - 3 Velocidades"); // NOI18N
        getContentPane().add(f1Info7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        f1Info8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info8.setForeground(new java.awt.Color(255, 255, 255));
        f1Info8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info8.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(f1Info8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        f1Info9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        f1Info9.setForeground(new java.awt.Color(255, 255, 255));
        f1Info9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        f1Info9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(f1Info9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        hotrodT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        hotrodT.setForeground(new java.awt.Color(255, 255, 255));
        hotrodT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotrodT.setText("FORD 37 Hot Rod");
        getContentPane().add(hotrodT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        hotrodInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        hotrodInfo1.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(hotrodInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        hotrodInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo2.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo2.setText("POTÊNCIA: 162CV"); // NOI18N
        getContentPane().add(hotrodInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        hotrodInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo3.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo3.setText("MOTOR: 4.0 V6"); // NOI18N
        getContentPane().add(hotrodInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        hotrodInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo4.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo4.setText("ANO FABRICAÇÃO/ANO MODELO: 1937/1937"); // NOI18N
        getContentPane().add(hotrodInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        hotrodInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo5.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo5.setText("COR: Laranja"); // NOI18N
        getContentPane().add(hotrodInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        hotrodInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo6.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo6.setText("PORTAS: 2"); // NOI18N
        getContentPane().add(hotrodInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        hotrodInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo7.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo7.setText("QUILOMETRAGEM: 1.200"); // NOI18N
        getContentPane().add(hotrodInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        hotrodInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo8.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo8.setText("OCUPANTES: 2"); // NOI18N
        getContentPane().add(hotrodInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));

        hotrodInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        hotrodInfo9.setForeground(new java.awt.Color(255, 255, 255));
        hotrodInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hotrodInfo9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(hotrodInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 330, 30));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_f1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_f1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/f1/F1-1.png"))); // NOI18N
        jtp_f1.addTab("1/4", f11);

        f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/f1/F1-2.png"))); // NOI18N
        jtp_f1.addTab("2/4", f12);

        f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/f1/F1-3.png"))); // NOI18N
        jtp_f1.addTab("3/4", f13);

        f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/f1/F1-4.png"))); // NOI18N
        jtp_f1.addTab("4/4", f14);

        getContentPane().add(jtp_f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 380, 220));

        jtp_hotrod.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_hotrod.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        hotrod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/hotrod/Hotrod1.png"))); // NOI18N
        jtp_hotrod.addTab("1/4", hotrod1);

        hotrod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/f1/F1-2.png"))); // NOI18N
        jtp_hotrod.addTab("2/4", hotrod2);

        hotrod3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/hotrod/Hotrod3.png"))); // NOI18N
        jtp_hotrod.addTab("3/4", hotrod3);

        hotrod4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/hotrod/Hotrod4.png"))); // NOI18N
        jtp_hotrod.addTab("4/4", hotrod4);

        getContentPane().add(jtp_hotrod, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 370, 220));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backFord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backFord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZFord3.this.dispose();
        
    }//GEN-LAST:event_btn_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backFord;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JLabel f14;
    private javax.swing.JLabel f1Info1;
    private javax.swing.JLabel f1Info2;
    private javax.swing.JLabel f1Info3;
    private javax.swing.JLabel f1Info4;
    private javax.swing.JLabel f1Info5;
    private javax.swing.JLabel f1Info6;
    private javax.swing.JLabel f1Info7;
    private javax.swing.JLabel f1Info8;
    private javax.swing.JLabel f1Info9;
    private javax.swing.JLabel f1T;
    private javax.swing.JLabel hotrod1;
    private javax.swing.JLabel hotrod2;
    private javax.swing.JLabel hotrod3;
    private javax.swing.JLabel hotrod4;
    private javax.swing.JLabel hotrodInfo1;
    private javax.swing.JLabel hotrodInfo2;
    private javax.swing.JLabel hotrodInfo3;
    private javax.swing.JLabel hotrodInfo4;
    private javax.swing.JLabel hotrodInfo5;
    private javax.swing.JLabel hotrodInfo6;
    private javax.swing.JLabel hotrodInfo7;
    private javax.swing.JLabel hotrodInfo8;
    private javax.swing.JLabel hotrodInfo9;
    private javax.swing.JLabel hotrodT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_f1;
    private javax.swing.JTabbedPane jtp_hotrod;
    // End of variables declaration//GEN-END:variables
}
