/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZFord2 extends javax.swing.JFrame {

    /**
     * Creates new form ZFord
     */
    public ZFord2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maverickT = new javax.swing.JLabel();
        maverickInfo1 = new javax.swing.JLabel();
        maverickInfo2 = new javax.swing.JLabel();
        maverickInfo3 = new javax.swing.JLabel();
        maverickInfo4 = new javax.swing.JLabel();
        maverickInfo5 = new javax.swing.JLabel();
        maverickInfo6 = new javax.swing.JLabel();
        maverickInfo7 = new javax.swing.JLabel();
        maverickInfo8 = new javax.swing.JLabel();
        maverickInfo9 = new javax.swing.JLabel();
        thunderbirdT = new javax.swing.JLabel();
        thunderbirdInfo1 = new javax.swing.JLabel();
        thunderbirdInfo2 = new javax.swing.JLabel();
        thunderbirdInfo3 = new javax.swing.JLabel();
        thunderbirdInfo4 = new javax.swing.JLabel();
        thunderbirdInfo5 = new javax.swing.JLabel();
        thunderbirdInfo6 = new javax.swing.JLabel();
        thunderbirdInfo7 = new javax.swing.JLabel();
        thunderbirdInfo8 = new javax.swing.JLabel();
        thunderbirdInfo9 = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        btn_proxima = new javax.swing.JButton();
        jtp_maverick = new javax.swing.JTabbedPane();
        maverick1 = new javax.swing.JLabel();
        maverick2 = new javax.swing.JLabel();
        maverick3 = new javax.swing.JLabel();
        maverick4 = new javax.swing.JLabel();
        jtp_thunderbird = new javax.swing.JTabbedPane();
        thunderbird1 = new javax.swing.JLabel();
        thunderbird2 = new javax.swing.JLabel();
        thunderbird3 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        backFord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ford 2/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maverickT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        maverickT.setForeground(new java.awt.Color(255, 255, 255));
        maverickT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maverickT.setText("FORD Maverick 302 V8");
        getContentPane().add(maverickT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        maverickInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        maverickInfo1.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(maverickInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        maverickInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo2.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo2.setText("POTÊNCIA: 400 CV"); // NOI18N
        getContentPane().add(maverickInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        maverickInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo3.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo3.setText("MOTOR: 302 pol³ V8"); // NOI18N
        getContentPane().add(maverickInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        maverickInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo4.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo4.setText("ANO FABRICAÇÃO/ANO MODELO: 1978/1978"); // NOI18N
        getContentPane().add(maverickInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        maverickInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo5.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo5.setText("COR: Cinza"); // NOI18N
        getContentPane().add(maverickInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        maverickInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo6.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo6.setText("CÂMBIO: Manual - 4 Velocidades"); // NOI18N
        getContentPane().add(maverickInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        maverickInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo7.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(maverickInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        maverickInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo8.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo8.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(maverickInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        maverickInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        maverickInfo9.setForeground(new java.awt.Color(255, 255, 255));
        maverickInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maverickInfo9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(maverickInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        thunderbirdT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        thunderbirdT.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thunderbirdT.setText("FORD Thunderbird V8");
        getContentPane().add(thunderbirdT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        thunderbirdInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        thunderbirdInfo1.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(thunderbirdInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        thunderbirdInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo2.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo2.setText("POTÊNCIA: 198 CV"); // NOI18N
        getContentPane().add(thunderbirdInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        thunderbirdInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo3.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo3.setText("MOTOR: 292 pol³ V8"); // NOI18N
        getContentPane().add(thunderbirdInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        thunderbirdInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo4.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo4.setText("ANO FABRICAÇÃO/ANO MODELO: 1955/1955"); // NOI18N
        getContentPane().add(thunderbirdInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        thunderbirdInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo5.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo5.setText("COR: Raven Black"); // NOI18N
        getContentPane().add(thunderbirdInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        thunderbirdInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo6.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo6.setText("QUILOMETRAGEM: 20.095 milhas"); // NOI18N
        getContentPane().add(thunderbirdInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        thunderbirdInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo7.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo7.setText("VELOCIDADE MÁXIMA: 180 km/h"); // NOI18N
        getContentPane().add(thunderbirdInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        thunderbirdInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo8.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo8.setText("ACELERAÇÃO 0-100KM/H: 9,4 segundos"); // NOI18N
        getContentPane().add(thunderbirdInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));

        thunderbirdInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        thunderbirdInfo9.setForeground(new java.awt.Color(255, 255, 255));
        thunderbirdInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thunderbirdInfo9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(thunderbirdInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 330, 30));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 100, 30));

        jtp_maverick.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_maverick.setToolTipText("");
        jtp_maverick.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        maverick1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/maverick/Maverick1.png"))); // NOI18N
        jtp_maverick.addTab("1/4", maverick1);

        maverick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/maverick/Maverick2.png"))); // NOI18N
        jtp_maverick.addTab("2/4", maverick2);

        maverick3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/maverick/Maverick3.png"))); // NOI18N
        jtp_maverick.addTab("3/4", maverick3);

        maverick4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/maverick/Maverick4.png"))); // NOI18N
        jtp_maverick.addTab("4/4", maverick4);

        getContentPane().add(jtp_maverick, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_thunderbird.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_thunderbird.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        thunderbird1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/thunderbird/Thunderbird1.png"))); // NOI18N
        jtp_thunderbird.addTab("1/3", thunderbird1);

        thunderbird2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/thunderbird/Thunderbird2.png"))); // NOI18N
        jtp_thunderbird.addTab("2/3", thunderbird2);

        thunderbird3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/thunderbird/Thunderbird3.png"))); // NOI18N
        jtp_thunderbird.addTab("3/3", thunderbird3);

        getContentPane().add(jtp_thunderbird, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 370, 230));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backFord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backFord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZFord2.this.dispose();

    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZFord3 f3 = new ZFord3();
        f3.setVisible(true);

    }//GEN-LAST:event_btn_proximaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backFord;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_maverick;
    private javax.swing.JTabbedPane jtp_thunderbird;
    private javax.swing.JLabel maverick1;
    private javax.swing.JLabel maverick2;
    private javax.swing.JLabel maverick3;
    private javax.swing.JLabel maverick4;
    private javax.swing.JLabel maverickInfo1;
    private javax.swing.JLabel maverickInfo2;
    private javax.swing.JLabel maverickInfo3;
    private javax.swing.JLabel maverickInfo4;
    private javax.swing.JLabel maverickInfo5;
    private javax.swing.JLabel maverickInfo6;
    private javax.swing.JLabel maverickInfo7;
    private javax.swing.JLabel maverickInfo8;
    private javax.swing.JLabel maverickInfo9;
    private javax.swing.JLabel maverickT;
    private javax.swing.JLabel thunderbird1;
    private javax.swing.JLabel thunderbird2;
    private javax.swing.JLabel thunderbird3;
    private javax.swing.JLabel thunderbirdInfo1;
    private javax.swing.JLabel thunderbirdInfo2;
    private javax.swing.JLabel thunderbirdInfo3;
    private javax.swing.JLabel thunderbirdInfo4;
    private javax.swing.JLabel thunderbirdInfo5;
    private javax.swing.JLabel thunderbirdInfo6;
    private javax.swing.JLabel thunderbirdInfo7;
    private javax.swing.JLabel thunderbirdInfo8;
    private javax.swing.JLabel thunderbirdInfo9;
    private javax.swing.JLabel thunderbirdT;
    // End of variables declaration//GEN-END:variables
}
