/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZFord extends javax.swing.JFrame {

    /**
     * Creates new form ZFord
     */
    public ZFord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cobraT = new javax.swing.JLabel();
        cobraInfo1 = new javax.swing.JLabel();
        cobraInfo2 = new javax.swing.JLabel();
        cobraInfo3 = new javax.swing.JLabel();
        cobraInfo4 = new javax.swing.JLabel();
        cobraInfo5 = new javax.swing.JLabel();
        cobraInfo6 = new javax.swing.JLabel();
        cobraInfo7 = new javax.swing.JLabel();
        cobraInfo8 = new javax.swing.JLabel();
        cobraInfo9 = new javax.swing.JLabel();
        fairlaneT = new javax.swing.JLabel();
        fairlaneInfo1 = new javax.swing.JLabel();
        fairlaneInfo2 = new javax.swing.JLabel();
        fairlaneInfo3 = new javax.swing.JLabel();
        fairlaneInfo4 = new javax.swing.JLabel();
        fairlaneInfo5 = new javax.swing.JLabel();
        fairlaneInfo6 = new javax.swing.JLabel();
        fairlaneInfo7 = new javax.swing.JLabel();
        fairlaneInfo8 = new javax.swing.JLabel();
        fairlaneInfo9 = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_cobra = new javax.swing.JTabbedPane();
        cobra1 = new javax.swing.JLabel();
        cobra2 = new javax.swing.JLabel();
        cobra3 = new javax.swing.JLabel();
        cobra4 = new javax.swing.JLabel();
        jtp_fairlane = new javax.swing.JTabbedPane();
        fairlane1 = new javax.swing.JLabel();
        fairlane2 = new javax.swing.JLabel();
        fairlane3 = new javax.swing.JLabel();
        fairlane4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        backFord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ford 1/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cobraT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        cobraT.setForeground(new java.awt.Color(255, 255, 255));
        cobraT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cobraT.setText("FORD Cobra");
        getContentPane().add(cobraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        cobraInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        cobraInfo1.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(cobraInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        cobraInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo2.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo2.setText("POTÊNCIA: 199 CV"); // NOI18N
        getContentPane().add(cobraInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        cobraInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo3.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo3.setText("MOTOR: 302 pol³ V8"); // NOI18N
        getContentPane().add(cobraInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        cobraInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo4.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo4.setText("ANO FABRICAÇÃO/ANO MODELO: 1968/1968"); // NOI18N
        getContentPane().add(cobraInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        cobraInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo5.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo5.setText("COR: Cinza Iridium"); // NOI18N
        getContentPane().add(cobraInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        cobraInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo6.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo6.setText("PORTAS: 2"); // NOI18N
        getContentPane().add(cobraInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        cobraInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo7.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo7.setText("QUILOMETRAGEM: 1.045"); // NOI18N
        getContentPane().add(cobraInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        cobraInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo8.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo8.setText("ACELERAÇÃO 0-100KM/H: 11,5 Segundos"); // NOI18N
        getContentPane().add(cobraInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        cobraInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        cobraInfo9.setForeground(new java.awt.Color(255, 255, 255));
        cobraInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cobraInfo9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(cobraInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        fairlaneT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        fairlaneT.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fairlaneT.setText("FORD Fairlane 500");
        getContentPane().add(fairlaneT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 330, 30));

        fairlaneInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        fairlaneInfo1.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(fairlaneInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 330, 30));

        fairlaneInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo2.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo2.setText("POTÊNCIA: 200HP"); // NOI18N
        getContentPane().add(fairlaneInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 330, 30));

        fairlaneInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo3.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo3.setText("VELOCIDADE MÁXIMA: 175Km/h"); // NOI18N
        getContentPane().add(fairlaneInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 30));

        fairlaneInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo4.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo4.setText("ANO FABRICAÇÃO/ANO MODELO: 1966/1966"); // NOI18N
        getContentPane().add(fairlaneInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 330, 30));

        fairlaneInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo5.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo5.setText("COR: Ivy Green"); // NOI18N
        getContentPane().add(fairlaneInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 330, 30));

        fairlaneInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo6.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo6.setText("PORTAS: 2"); // NOI18N
        getContentPane().add(fairlaneInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 330, 30));

        fairlaneInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo7.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo7.setText("TRAÇÃO: Traseira"); // NOI18N
        getContentPane().add(fairlaneInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 330, 30));

        fairlaneInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo8.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo8.setText("ACELERAÇÃO 0-100KM/H: 10,6 segundos"); // NOI18N
        getContentPane().add(fairlaneInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 330, 30));

        fairlaneInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fairlaneInfo9.setForeground(new java.awt.Color(255, 255, 255));
        fairlaneInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fairlaneInfo9.setText("DIREÇÃO HIDRÁULICA: Sim"); // NOI18N
        getContentPane().add(fairlaneInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 330, 30));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 100, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_cobra.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_cobra.setToolTipText("");
        jtp_cobra.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        cobra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/cobra/Cobra1.png"))); // NOI18N
        jtp_cobra.addTab("1/4", cobra1);

        cobra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/cobra/Cobra2.png"))); // NOI18N
        jtp_cobra.addTab("2/4", cobra2);

        cobra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/cobra/Cobra3.png"))); // NOI18N
        jtp_cobra.addTab("3/4", cobra3);

        cobra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/cobra/Cobra4.png"))); // NOI18N
        jtp_cobra.addTab("4/4", cobra4);

        getContentPane().add(jtp_cobra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_fairlane.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_fairlane.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        fairlane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/fairlane/Fairlane1.png"))); // NOI18N
        jtp_fairlane.addTab("1/4", fairlane1);

        fairlane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/fairlane/Fairlane2.png"))); // NOI18N
        jtp_fairlane.addTab("2/4", fairlane2);

        fairlane3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/fairlane/Fairlane3.png"))); // NOI18N
        jtp_fairlane.addTab("3/4", fairlane3);

        fairlane4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/ford/fairlane/Fairlane4.png"))); // NOI18N
        jtp_fairlane.addTab("4/4", fairlane4);

        getContentPane().add(jtp_fairlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 370, 230));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        backFord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backFord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZFord2 f2 = new ZFord2();
        f2.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZFord.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backFord;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel cobra1;
    private javax.swing.JLabel cobra2;
    private javax.swing.JLabel cobra3;
    private javax.swing.JLabel cobra4;
    private javax.swing.JLabel cobraInfo1;
    private javax.swing.JLabel cobraInfo2;
    private javax.swing.JLabel cobraInfo3;
    private javax.swing.JLabel cobraInfo4;
    private javax.swing.JLabel cobraInfo5;
    private javax.swing.JLabel cobraInfo6;
    private javax.swing.JLabel cobraInfo7;
    private javax.swing.JLabel cobraInfo8;
    private javax.swing.JLabel cobraInfo9;
    private javax.swing.JLabel cobraT;
    private javax.swing.JLabel fairlane1;
    private javax.swing.JLabel fairlane2;
    private javax.swing.JLabel fairlane3;
    private javax.swing.JLabel fairlane4;
    private javax.swing.JLabel fairlaneInfo1;
    private javax.swing.JLabel fairlaneInfo2;
    private javax.swing.JLabel fairlaneInfo3;
    private javax.swing.JLabel fairlaneInfo4;
    private javax.swing.JLabel fairlaneInfo5;
    private javax.swing.JLabel fairlaneInfo6;
    private javax.swing.JLabel fairlaneInfo7;
    private javax.swing.JLabel fairlaneInfo8;
    private javax.swing.JLabel fairlaneInfo9;
    private javax.swing.JLabel fairlaneT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_cobra;
    private javax.swing.JTabbedPane jtp_fairlane;
    // End of variables declaration//GEN-END:variables
}
