/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZHarley2 extends javax.swing.JFrame {

    /**
     * Creates new form ZHarley
     */
    public ZHarley2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        superglideT = new javax.swing.JLabel();
        superglideInfo1 = new javax.swing.JLabel();
        superglideInfo2 = new javax.swing.JLabel();
        superglideInfo3 = new javax.swing.JLabel();
        superglideInfo4 = new javax.swing.JLabel();
        superglideInfo5 = new javax.swing.JLabel();
        tourglideT = new javax.swing.JLabel();
        tourglideInfo1 = new javax.swing.JLabel();
        tourglideInfo2 = new javax.swing.JLabel();
        tourglideInfo3 = new javax.swing.JLabel();
        tourglideInfo4 = new javax.swing.JLabel();
        tourglideInfo5 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        btn_proxima = new javax.swing.JButton();
        jtp_superglide = new javax.swing.JTabbedPane();
        superglide1 = new javax.swing.JLabel();
        superglide2 = new javax.swing.JLabel();
        superglide3 = new javax.swing.JLabel();
        superglide4 = new javax.swing.JLabel();
        jtp_tourglide = new javax.swing.JTabbedPane();
        tourglide1 = new javax.swing.JLabel();
        tourglide2 = new javax.swing.JLabel();
        tourglide3 = new javax.swing.JLabel();
        backHarley = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Harley-Davidson 2/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        superglideT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        superglideT.setForeground(new java.awt.Color(255, 255, 255));
        superglideT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        superglideT.setText("HARLEY-DAVIDSON Super Glide");
        getContentPane().add(superglideT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 260, 30));

        superglideInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        superglideInfo1.setForeground(new java.awt.Color(255, 255, 255));
        superglideInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        superglideInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(superglideInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 330, 30));

        superglideInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        superglideInfo2.setForeground(new java.awt.Color(255, 255, 255));
        superglideInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        superglideInfo2.setText("ANO FABRICAÇÃO: 1983"); // NOI18N
        getContentPane().add(superglideInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 30));

        superglideInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        superglideInfo3.setForeground(new java.awt.Color(255, 255, 255));
        superglideInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        superglideInfo3.setText("QUILOMETRAGEM: 44.400"); // NOI18N
        getContentPane().add(superglideInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 330, 30));

        superglideInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        superglideInfo4.setForeground(new java.awt.Color(255, 255, 255));
        superglideInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        superglideInfo4.setText("COR PRIMÁRIA: Vermelho Claret"); // NOI18N
        getContentPane().add(superglideInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 330, 30));

        superglideInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        superglideInfo5.setForeground(new java.awt.Color(255, 255, 255));
        superglideInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        superglideInfo5.setText("MOTOR:  Isolation Mounted OHV V-Twin"); // NOI18N
        getContentPane().add(superglideInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 330, 30));

        tourglideT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        tourglideT.setForeground(new java.awt.Color(255, 255, 255));
        tourglideT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tourglideT.setText("HARLEY-DAVIDSON Tour Glide");
        getContentPane().add(tourglideT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 260, 30));

        tourglideInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        tourglideInfo1.setForeground(new java.awt.Color(255, 255, 255));
        tourglideInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tourglideInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(tourglideInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 330, 30));

        tourglideInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tourglideInfo2.setForeground(new java.awt.Color(255, 255, 255));
        tourglideInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tourglideInfo2.setText("ANO FABRICAÇÃO: 1980"); // NOI18N
        getContentPane().add(tourglideInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 330, 30));

        tourglideInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tourglideInfo3.setForeground(new java.awt.Color(255, 255, 255));
        tourglideInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tourglideInfo3.setText("QUILOMETRAGEM: 63.400"); // NOI18N
        getContentPane().add(tourglideInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 330, 30));

        tourglideInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tourglideInfo4.setForeground(new java.awt.Color(255, 255, 255));
        tourglideInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tourglideInfo4.setText("COR PRIMÁRIA: Preto"); // NOI18N
        getContentPane().add(tourglideInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 330, 30));

        tourglideInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tourglideInfo5.setForeground(new java.awt.Color(255, 255, 255));
        tourglideInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tourglideInfo5.setText("MOTOR:  V-Twin"); // NOI18N
        getContentPane().add(tourglideInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 330, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_anterior.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        jtp_superglide.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_superglide.setToolTipText("");
        jtp_superglide.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        superglide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/superglide/Super1.png"))); // NOI18N
        jtp_superglide.addTab("1/4", superglide1);

        superglide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/superglide/Super2.png"))); // NOI18N
        jtp_superglide.addTab("2/4", superglide2);

        superglide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/superglide/Super3.png"))); // NOI18N
        jtp_superglide.addTab("3/4", superglide3);

        superglide4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/superglide/Super4.png"))); // NOI18N
        jtp_superglide.addTab("4/4", superglide4);

        getContentPane().add(jtp_superglide, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, 190));

        jtp_tourglide.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_tourglide.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        tourglide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/tourglide/Tour1.png"))); // NOI18N
        jtp_tourglide.addTab("1/3", tourglide1);

        tourglide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/tourglide/Tour2.png"))); // NOI18N
        jtp_tourglide.addTab("2/3", tourglide2);

        tourglide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/tourglide/Tour3.png"))); // NOI18N
        jtp_tourglide.addTab("3/3", tourglide3);

        getContentPane().add(jtp_tourglide, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 290, 190));

        backHarley.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backHarley, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed

        ZHarley2.this.dispose();
        
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZHarley3 h3 = new ZHarley3();
        h3.setVisible(true);

    }//GEN-LAST:event_btn_proximaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backHarley;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_superglide;
    private javax.swing.JTabbedPane jtp_tourglide;
    private javax.swing.JLabel superglide1;
    private javax.swing.JLabel superglide2;
    private javax.swing.JLabel superglide3;
    private javax.swing.JLabel superglide4;
    private javax.swing.JLabel superglideInfo1;
    private javax.swing.JLabel superglideInfo2;
    private javax.swing.JLabel superglideInfo3;
    private javax.swing.JLabel superglideInfo4;
    private javax.swing.JLabel superglideInfo5;
    private javax.swing.JLabel superglideT;
    private javax.swing.JLabel tourglide1;
    private javax.swing.JLabel tourglide2;
    private javax.swing.JLabel tourglide3;
    private javax.swing.JLabel tourglideInfo1;
    private javax.swing.JLabel tourglideInfo2;
    private javax.swing.JLabel tourglideInfo3;
    private javax.swing.JLabel tourglideInfo4;
    private javax.swing.JLabel tourglideInfo5;
    private javax.swing.JLabel tourglideT;
    // End of variables declaration//GEN-END:variables
}
