/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZHarley extends javax.swing.JFrame {

    /**
     * Creates new form ZHarley
     */
    public ZHarley() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynaT = new javax.swing.JLabel();
        dynaInfo1 = new javax.swing.JLabel();
        dynaInfo2 = new javax.swing.JLabel();
        dynaInfo3 = new javax.swing.JLabel();
        dynaInfo4 = new javax.swing.JLabel();
        dynaInfo5 = new javax.swing.JLabel();
        dynaInfo6 = new javax.swing.JLabel();
        heritageT = new javax.swing.JLabel();
        heritageInfo1 = new javax.swing.JLabel();
        heritageInfo2 = new javax.swing.JLabel();
        heritageInfo3 = new javax.swing.JLabel();
        heritageInfo4 = new javax.swing.JLabel();
        heritageInfo5 = new javax.swing.JLabel();
        heritageInfo6 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_dyna = new javax.swing.JTabbedPane();
        dyna1 = new javax.swing.JLabel();
        dyna2 = new javax.swing.JLabel();
        jtp_heritage = new javax.swing.JTabbedPane();
        heritage1 = new javax.swing.JLabel();
        heritage2 = new javax.swing.JLabel();
        heritage3 = new javax.swing.JLabel();
        backHarley = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Harley-Davidson 1/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynaT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        dynaT.setForeground(new java.awt.Color(255, 255, 255));
        dynaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dynaT.setText("HARLEY-DAVIDSON Dyna Convertible");
        getContentPane().add(dynaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 310, 30));

        dynaInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        dynaInfo1.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(dynaInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 330, 30));

        dynaInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dynaInfo2.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo2.setText("ANO FABRICAÇÃO: 2000"); // NOI18N
        getContentPane().add(dynaInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 30));

        dynaInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dynaInfo3.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo3.setText("QUILOMETRAGEM: 43.450"); // NOI18N
        getContentPane().add(dynaInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 330, 30));

        dynaInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dynaInfo4.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo4.setText("COR PRIMÁRIA: Burgundy"); // NOI18N
        getContentPane().add(dynaInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 330, 30));

        dynaInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dynaInfo5.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo5.setText("COR SECUNDÁRIA:  Preto"); // NOI18N
        getContentPane().add(dynaInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 330, 30));

        dynaInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        dynaInfo6.setForeground(new java.awt.Color(255, 255, 255));
        dynaInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dynaInfo6.setText("MOTOR: V Twin"); // NOI18N
        getContentPane().add(dynaInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 330, 30));

        heritageT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        heritageT.setForeground(new java.awt.Color(255, 255, 255));
        heritageT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heritageT.setText("HARLEY-DAVIDSON Heritage Springer");
        getContentPane().add(heritageT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 310, 30));

        heritageInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        heritageInfo1.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(heritageInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 330, 30));

        heritageInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        heritageInfo2.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo2.setText("ANO FABRICAÇÃO: 2002"); // NOI18N
        getContentPane().add(heritageInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 330, 30));

        heritageInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        heritageInfo3.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo3.setText("COR PRIMÁRIA: Verde"); // NOI18N
        getContentPane().add(heritageInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 330, 30));

        heritageInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        heritageInfo4.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo4.setText("COR SECUNDÁRIA:  Preto"); // NOI18N
        getContentPane().add(heritageInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 330, 30));

        heritageInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        heritageInfo5.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo5.setText("QUILOMETRAGEM: 45.780"); // NOI18N
        getContentPane().add(heritageInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 330, 30));

        heritageInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        heritageInfo6.setForeground(new java.awt.Color(255, 255, 255));
        heritageInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heritageInfo6.setText("MOTOR: 88b Twin Cam"); // NOI18N
        getContentPane().add(heritageInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 330, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_dyna.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_dyna.setToolTipText("");
        jtp_dyna.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        dyna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/dyna/Dyna1.png"))); // NOI18N
        jtp_dyna.addTab("1/2", dyna1);

        dyna2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/dyna/Dyna2.png"))); // NOI18N
        jtp_dyna.addTab("2/2", dyna2);

        getContentPane().add(jtp_dyna, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, 190));

        jtp_heritage.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_heritage.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        heritage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/heritage/Heritage1.png"))); // NOI18N
        jtp_heritage.addTab("1/3", heritage1);

        heritage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/heritage/Heritage2.png"))); // NOI18N
        jtp_heritage.addTab("2/3", heritage2);

        heritage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/heritage/Heritage3.png"))); // NOI18N
        jtp_heritage.addTab("3/3", heritage3);

        getContentPane().add(jtp_heritage, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 290, 190));

        backHarley.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backHarley, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZHarley2 h2 = new ZHarley2();
        h2.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZHarley.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backHarley;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel dyna1;
    private javax.swing.JLabel dyna2;
    private javax.swing.JLabel dynaInfo1;
    private javax.swing.JLabel dynaInfo2;
    private javax.swing.JLabel dynaInfo3;
    private javax.swing.JLabel dynaInfo4;
    private javax.swing.JLabel dynaInfo5;
    private javax.swing.JLabel dynaInfo6;
    private javax.swing.JLabel dynaT;
    private javax.swing.JLabel heritage1;
    private javax.swing.JLabel heritage2;
    private javax.swing.JLabel heritage3;
    private javax.swing.JLabel heritageInfo1;
    private javax.swing.JLabel heritageInfo2;
    private javax.swing.JLabel heritageInfo3;
    private javax.swing.JLabel heritageInfo4;
    private javax.swing.JLabel heritageInfo5;
    private javax.swing.JLabel heritageInfo6;
    private javax.swing.JLabel heritageT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_dyna;
    private javax.swing.JTabbedPane jtp_heritage;
    // End of variables declaration//GEN-END:variables
}
