/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZHarley3 extends javax.swing.JFrame {

    /**
     * Creates new form ZHarley
     */
    public ZHarley3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fxrT = new javax.swing.JLabel();
        fxrInfo1 = new javax.swing.JLabel();
        fxrInfo2 = new javax.swing.JLabel();
        fxrInfo3 = new javax.swing.JLabel();
        fxrInfo4 = new javax.swing.JLabel();
        fxrInfo5 = new javax.swing.JLabel();
        sportsterT = new javax.swing.JLabel();
        sportsterInfo1 = new javax.swing.JLabel();
        sportsterInfo2 = new javax.swing.JLabel();
        sportsterInfo3 = new javax.swing.JLabel();
        sportsterInfo4 = new javax.swing.JLabel();
        sportsterInfo5 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jtp_sportster = new javax.swing.JTabbedPane();
        sportster1 = new javax.swing.JLabel();
        sportster2 = new javax.swing.JLabel();
        jtp_fxr = new javax.swing.JTabbedPane();
        fxr1 = new javax.swing.JLabel();
        fxr2 = new javax.swing.JLabel();
        fxr3 = new javax.swing.JLabel();
        backHarley = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Harley-Davidson 3/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fxrT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        fxrT.setForeground(new java.awt.Color(255, 255, 255));
        fxrT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fxrT.setText("HARLEY-DAVIDSON FXR");
        getContentPane().add(fxrT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 260, 30));

        fxrInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        fxrInfo1.setForeground(new java.awt.Color(255, 255, 255));
        fxrInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fxrInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(fxrInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 330, 30));

        fxrInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fxrInfo2.setForeground(new java.awt.Color(255, 255, 255));
        fxrInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fxrInfo2.setText("ANO FABRICAÇÃO: 1989"); // NOI18N
        getContentPane().add(fxrInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 30));

        fxrInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fxrInfo3.setForeground(new java.awt.Color(255, 255, 255));
        fxrInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fxrInfo3.setText("QUILOMETRAGEM: 56.320"); // NOI18N
        getContentPane().add(fxrInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 330, 30));

        fxrInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fxrInfo4.setForeground(new java.awt.Color(255, 255, 255));
        fxrInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fxrInfo4.setText("COR: Vermelho cereja"); // NOI18N
        getContentPane().add(fxrInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 330, 30));

        fxrInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        fxrInfo5.setForeground(new java.awt.Color(255, 255, 255));
        fxrInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fxrInfo5.setText("MOTOR:  EVO"); // NOI18N
        getContentPane().add(fxrInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 330, 30));

        sportsterT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        sportsterT.setForeground(new java.awt.Color(255, 255, 255));
        sportsterT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sportsterT.setText("HARLEY-DAVIDSON Sportster");
        getContentPane().add(sportsterT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 260, 30));

        sportsterInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        sportsterInfo1.setForeground(new java.awt.Color(255, 255, 255));
        sportsterInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportsterInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(sportsterInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 330, 30));

        sportsterInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportsterInfo2.setForeground(new java.awt.Color(255, 255, 255));
        sportsterInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportsterInfo2.setText("ANO FABRICAÇÃO: 1975"); // NOI18N
        getContentPane().add(sportsterInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 330, 30));

        sportsterInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportsterInfo3.setForeground(new java.awt.Color(255, 255, 255));
        sportsterInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportsterInfo3.setText("COR: Preto"); // NOI18N
        getContentPane().add(sportsterInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 330, 30));

        sportsterInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportsterInfo4.setForeground(new java.awt.Color(255, 255, 255));
        sportsterInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportsterInfo4.setText("MOTOR: 93 CI"); // NOI18N
        getContentPane().add(sportsterInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 330, 30));

        sportsterInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportsterInfo5.setForeground(new java.awt.Color(255, 255, 255));
        sportsterInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportsterInfo5.setText("QUILOMETRAGEM: 53.750"); // NOI18N
        getContentPane().add(sportsterInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 330, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Anterior");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_sportster.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_sportster.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        sportster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/sportster/Sportster1.png"))); // NOI18N
        jtp_sportster.addTab("1/2", sportster1);

        sportster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/sportster/Sportster2.png"))); // NOI18N
        jtp_sportster.addTab("2/2", sportster2);

        getContentPane().add(jtp_sportster, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 290, 190));

        jtp_fxr.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_fxr.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        fxr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/fxr/FXR1.png"))); // NOI18N
        jtp_fxr.addTab("1/3", fxr1);

        fxr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/fxr/FXR2.png"))); // NOI18N
        jtp_fxr.addTab("2/3", fxr2);

        fxr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/harley/fxr/FXR3.png"))); // NOI18N
        jtp_fxr.addTab("3/3", fxr3);

        getContentPane().add(jtp_fxr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, 190));

        backHarley.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backHarley, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZHarley3.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backHarley;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel fxr1;
    private javax.swing.JLabel fxr2;
    private javax.swing.JLabel fxr3;
    private javax.swing.JLabel fxrInfo1;
    private javax.swing.JLabel fxrInfo2;
    private javax.swing.JLabel fxrInfo3;
    private javax.swing.JLabel fxrInfo4;
    private javax.swing.JLabel fxrInfo5;
    private javax.swing.JLabel fxrT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_fxr;
    private javax.swing.JTabbedPane jtp_sportster;
    private javax.swing.JLabel sportster1;
    private javax.swing.JLabel sportster2;
    private javax.swing.JLabel sportsterInfo1;
    private javax.swing.JLabel sportsterInfo2;
    private javax.swing.JLabel sportsterInfo3;
    private javax.swing.JLabel sportsterInfo4;
    private javax.swing.JLabel sportsterInfo5;
    private javax.swing.JLabel sportsterT;
    // End of variables declaration//GEN-END:variables
}
