/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZPlymouth extends javax.swing.JFrame {

    /**
     * Creates new form ZPlymouth
     */
    public ZPlymouth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barracudaT = new javax.swing.JLabel();
        barracudaInfo1 = new javax.swing.JLabel();
        barracudaInfo2 = new javax.swing.JLabel();
        barracudaInfo3 = new javax.swing.JLabel();
        barracudaInfo4 = new javax.swing.JLabel();
        barracudaInfo5 = new javax.swing.JLabel();
        barracudaInfo6 = new javax.swing.JLabel();
        barracudaInfo7 = new javax.swing.JLabel();
        barracudaInfo8 = new javax.swing.JLabel();
        barracudaInfo9 = new javax.swing.JLabel();
        voyagerT = new javax.swing.JLabel();
        voyagerInfo1 = new javax.swing.JLabel();
        voyagerInfo2 = new javax.swing.JLabel();
        voyagerInfo3 = new javax.swing.JLabel();
        voyagerInfo4 = new javax.swing.JLabel();
        voyagerInfo5 = new javax.swing.JLabel();
        voyagerInfo6 = new javax.swing.JLabel();
        voyagerInfo7 = new javax.swing.JLabel();
        voyagerInfo8 = new javax.swing.JLabel();
        voyagerInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_proxima2 = new javax.swing.JButton();
        jtp_barracuda = new javax.swing.JTabbedPane();
        barracuda1 = new javax.swing.JLabel();
        barracuda2 = new javax.swing.JLabel();
        barracuda3 = new javax.swing.JLabel();
        barracuda4 = new javax.swing.JLabel();
        jtp_voyager = new javax.swing.JTabbedPane();
        voyager1 = new javax.swing.JLabel();
        voyager2 = new javax.swing.JLabel();
        voyager3 = new javax.swing.JLabel();
        backPlymouth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plymouth 1/2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barracudaT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        barracudaT.setForeground(new java.awt.Color(255, 255, 255));
        barracudaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barracudaT.setText("PLYMOUTH Barracuda AAR");
        getContentPane().add(barracudaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 310, 30));

        barracudaInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        barracudaInfo1.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(barracudaInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 310, 30));

        barracudaInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo2.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1974/1974"); // NOI18N
        getContentPane().add(barracudaInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 340, 30));

        barracudaInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo3.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo3.setText("COR: Verde "); // NOI18N
        getContentPane().add(barracudaInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 310, 30));

        barracudaInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo4.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo4.setText("QUILOMETRAGEM: 48.500 "); // NOI18N
        getContentPane().add(barracudaInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 310, 30));

        barracudaInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo5.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo5.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(barracudaInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 310, 30));

        barracudaInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo6.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo6.setText("MOTOR: V8 (5.9 litros)"); // NOI18N
        getContentPane().add(barracudaInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 310, 30));

        barracudaInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo7.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo7.setText("POTÊNCIA: 305 HP "); // NOI18N
        getContentPane().add(barracudaInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 310, 30));

        barracudaInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo8.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo8.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(barracudaInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 310, 30));

        barracudaInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        barracudaInfo9.setForeground(new java.awt.Color(255, 255, 255));
        barracudaInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barracudaInfo9.setText("CÂMBIO: Automático - 3 Velocidades "); // NOI18N
        getContentPane().add(barracudaInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 310, 30));

        voyagerT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        voyagerT.setForeground(new java.awt.Color(255, 255, 255));
        voyagerT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voyagerT.setText("PLYMOUTH Voyager");
        getContentPane().add(voyagerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 310, 30));

        voyagerInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        voyagerInfo1.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(voyagerInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 310, 30));

        voyagerInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo2.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1983/1983 "); // NOI18N
        getContentPane().add(voyagerInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 340, 30));

        voyagerInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo3.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo3.setText("COR: Vermelho "); // NOI18N
        getContentPane().add(voyagerInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 310, 30));

        voyagerInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo4.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo4.setText("QUILOMETRAGEM: 40.000 "); // NOI18N
        getContentPane().add(voyagerInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 310, 30));

        voyagerInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo5.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo5.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(voyagerInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 310, 30));

        voyagerInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo6.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo6.setText("MOTOR: V8 (5.2 litros)"); // NOI18N
        getContentPane().add(voyagerInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 310, 30));

        voyagerInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo7.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo7.setText("POTÊNCIA: 230 CV "); // NOI18N
        getContentPane().add(voyagerInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 310, 30));

        voyagerInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo8.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo8.setText("CÂMBIO: Automático - 3 Velocidades "); // NOI18N
        getContentPane().add(voyagerInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 310, 30));

        voyagerInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        voyagerInfo9.setForeground(new java.awt.Color(255, 255, 255));
        voyagerInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        voyagerInfo9.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(voyagerInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 310, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima2.setText("Próxima");
        btn_proxima2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proxima2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 100, 30));

        jtp_barracuda.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_barracuda.setToolTipText("");
        jtp_barracuda.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        barracuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/barracuda/barracuda1.png"))); // NOI18N
        jtp_barracuda.addTab("1/4", barracuda1);

        barracuda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/barracuda/barracuda2.png"))); // NOI18N
        jtp_barracuda.addTab("2/4", barracuda2);

        barracuda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/barracuda/barracuda3.png"))); // NOI18N
        jtp_barracuda.addTab("3/4", barracuda3);

        barracuda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/barracuda/barracuda4.png"))); // NOI18N
        jtp_barracuda.addTab("4/4", barracuda4);

        getContentPane().add(jtp_barracuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 350, 230));

        jtp_voyager.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_voyager.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        voyager1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/voyager/voyager1.png"))); // NOI18N
        jtp_voyager.addTab("1/3", voyager1);

        voyager2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/voyager/voyager2.png"))); // NOI18N
        jtp_voyager.addTab("2/3", voyager2);

        voyager3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/voyager/voyager3.png"))); // NOI18N
        jtp_voyager.addTab("3/3", voyager3);

        getContentPane().add(jtp_voyager, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 350, 230));

        backPlymouth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backPlymouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZPlymouth.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_proxima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proxima2ActionPerformed

        ZPlymouth2 p2 = new ZPlymouth2();
        p2.setVisible(true);
        
    }//GEN-LAST:event_btn_proxima2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backPlymouth;
    private javax.swing.JLabel barracuda1;
    private javax.swing.JLabel barracuda2;
    private javax.swing.JLabel barracuda3;
    private javax.swing.JLabel barracuda4;
    private javax.swing.JLabel barracudaInfo1;
    private javax.swing.JLabel barracudaInfo2;
    private javax.swing.JLabel barracudaInfo3;
    private javax.swing.JLabel barracudaInfo4;
    private javax.swing.JLabel barracudaInfo5;
    private javax.swing.JLabel barracudaInfo6;
    private javax.swing.JLabel barracudaInfo7;
    private javax.swing.JLabel barracudaInfo8;
    private javax.swing.JLabel barracudaInfo9;
    private javax.swing.JLabel barracudaT;
    private javax.swing.JButton btn_proxima2;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_barracuda;
    private javax.swing.JTabbedPane jtp_voyager;
    private javax.swing.JLabel voyager1;
    private javax.swing.JLabel voyager2;
    private javax.swing.JLabel voyager3;
    private javax.swing.JLabel voyagerInfo1;
    private javax.swing.JLabel voyagerInfo2;
    private javax.swing.JLabel voyagerInfo3;
    private javax.swing.JLabel voyagerInfo4;
    private javax.swing.JLabel voyagerInfo5;
    private javax.swing.JLabel voyagerInfo6;
    private javax.swing.JLabel voyagerInfo7;
    private javax.swing.JLabel voyagerInfo8;
    private javax.swing.JLabel voyagerInfo9;
    private javax.swing.JLabel voyagerT;
    // End of variables declaration//GEN-END:variables
}
