/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZPlymouth2 extends javax.swing.JFrame {

    /**
     * Creates new form ZPlymouth
     */
    public ZPlymouth2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sportfT = new javax.swing.JLabel();
        sportfInfo1 = new javax.swing.JLabel();
        sportfInfo2 = new javax.swing.JLabel();
        sportfInfo3 = new javax.swing.JLabel();
        sportfInfo4 = new javax.swing.JLabel();
        sportfInfo5 = new javax.swing.JLabel();
        sportfInfo6 = new javax.swing.JLabel();
        sportfInfo7 = new javax.swing.JLabel();
        sportfInfo8 = new javax.swing.JLabel();
        sportfInfo9 = new javax.swing.JLabel();
        gtxT = new javax.swing.JLabel();
        gtxInfo1 = new javax.swing.JLabel();
        gtxInfo2 = new javax.swing.JLabel();
        gtxInfo3 = new javax.swing.JLabel();
        gtxInfo4 = new javax.swing.JLabel();
        gtxInfo5 = new javax.swing.JLabel();
        gtxInfo6 = new javax.swing.JLabel();
        gtxInfo7 = new javax.swing.JLabel();
        gtxInfo8 = new javax.swing.JLabel();
        gtxInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jtp_sport = new javax.swing.JTabbedPane();
        sport1 = new javax.swing.JLabel();
        sport2 = new javax.swing.JLabel();
        sport3 = new javax.swing.JLabel();
        sport4 = new javax.swing.JLabel();
        jtp_gtx = new javax.swing.JTabbedPane();
        gtx1 = new javax.swing.JLabel();
        gtx2 = new javax.swing.JLabel();
        gtx3 = new javax.swing.JLabel();
        gtx4 = new javax.swing.JLabel();
        backPlymouth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plymouth 2/2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sportfT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        sportfT.setForeground(new java.awt.Color(255, 255, 255));
        sportfT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sportfT.setText("PLYMOUTH Sport Fury");
        getContentPane().add(sportfT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 310, 30));

        sportfInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        sportfInfo1.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(sportfInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 310, 30));

        sportfInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo2.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo2.setText("ANO FABRICAÇÃO: 1960"); // NOI18N
        getContentPane().add(sportfInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 310, 30));

        sportfInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo3.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo3.setText("POTÊNCIA: 200 HP "); // NOI18N
        getContentPane().add(sportfInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 310, 30));

        sportfInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo4.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo4.setText("CÂMBIO: Automático - 3 Velocidades "); // NOI18N
        getContentPane().add(sportfInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 310, 30));

        sportfInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo5.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo5.setText("MOTOR: V8 (5.2 litros)"); // NOI18N
        getContentPane().add(sportfInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 310, 30));

        sportfInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo6.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo6.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(sportfInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 310, 30));

        sportfInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo7.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo7.setText("COR: Vermelho"); // NOI18N
        getContentPane().add(sportfInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 310, 30));

        sportfInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo8.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo8.setText("QUILOMETRAGEM: 76.760"); // NOI18N
        getContentPane().add(sportfInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 310, 30));

        sportfInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        sportfInfo9.setForeground(new java.awt.Color(255, 255, 255));
        sportfInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sportfInfo9.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(sportfInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 310, 30));

        gtxT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        gtxT.setForeground(new java.awt.Color(255, 255, 255));
        gtxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gtxT.setText("PLYMOUTH GTX 440");
        getContentPane().add(gtxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 310, 30));

        gtxInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        gtxInfo1.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(gtxInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 310, 30));

        gtxInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo2.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo2.setText("ANO FABRICAÇÃO: 1971"); // NOI18N
        getContentPane().add(gtxInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 310, 30));

        gtxInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo3.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo3.setText("QUILOMETRAGEM: 120"); // NOI18N
        getContentPane().add(gtxInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 310, 30));

        gtxInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo4.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo4.setText("CÂMBIO: Manual"); // NOI18N
        getContentPane().add(gtxInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 310, 30));

        gtxInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo5.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo5.setText("COR PRIMÁRIA: Azul"); // NOI18N
        getContentPane().add(gtxInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 310, 30));

        gtxInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo6.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo6.setText("COR SECUNDÁRIA: Preto"); // NOI18N
        getContentPane().add(gtxInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 310, 30));

        gtxInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo7.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo7.setText("MOTOR: V8"); // NOI18N
        getContentPane().add(gtxInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 310, 30));

        gtxInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo8.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo8.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(gtxInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 310, 30));

        gtxInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtxInfo9.setForeground(new java.awt.Color(255, 255, 255));
        gtxInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtxInfo9.setText("POTÊNCIA: 440HP"); // NOI18N
        getContentPane().add(gtxInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 310, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Anterior");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_sport.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_sport.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        sport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/sport fury/Sport1.png"))); // NOI18N
        jtp_sport.addTab("1/4", sport1);

        sport2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/sport fury/Sport2.png"))); // NOI18N
        jtp_sport.addTab("2/4", sport2);

        sport3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/sport fury/Sport3.png"))); // NOI18N
        jtp_sport.addTab("3/4", sport3);

        sport4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/sport fury/Sport4.png"))); // NOI18N
        jtp_sport.addTab("4/4", sport4);

        getContentPane().add(jtp_sport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 350, 230));

        jtp_gtx.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_gtx.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        gtx1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/gtx/Gtx1.png"))); // NOI18N
        jtp_gtx.addTab("1/4", gtx1);

        gtx2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/gtx/Gtx2.png"))); // NOI18N
        jtp_gtx.addTab("2/4", gtx2);

        gtx3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/gtx/Gtx3.png"))); // NOI18N
        jtp_gtx.addTab("3/4", gtx3);

        gtx4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/plymouth/gtx/Gtx4.png"))); // NOI18N
        jtp_gtx.addTab("4/4", gtx4);

        getContentPane().add(jtp_gtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 350, 180));

        backPlymouth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backPlymouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZPlymouth2.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backPlymouth;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel gtx1;
    private javax.swing.JLabel gtx2;
    private javax.swing.JLabel gtx3;
    private javax.swing.JLabel gtx4;
    private javax.swing.JLabel gtxInfo1;
    private javax.swing.JLabel gtxInfo2;
    private javax.swing.JLabel gtxInfo3;
    private javax.swing.JLabel gtxInfo4;
    private javax.swing.JLabel gtxInfo5;
    private javax.swing.JLabel gtxInfo6;
    private javax.swing.JLabel gtxInfo7;
    private javax.swing.JLabel gtxInfo8;
    private javax.swing.JLabel gtxInfo9;
    private javax.swing.JLabel gtxT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_gtx;
    private javax.swing.JTabbedPane jtp_sport;
    private javax.swing.JLabel sport1;
    private javax.swing.JLabel sport2;
    private javax.swing.JLabel sport3;
    private javax.swing.JLabel sport4;
    private javax.swing.JLabel sportfInfo1;
    private javax.swing.JLabel sportfInfo2;
    private javax.swing.JLabel sportfInfo3;
    private javax.swing.JLabel sportfInfo4;
    private javax.swing.JLabel sportfInfo5;
    private javax.swing.JLabel sportfInfo6;
    private javax.swing.JLabel sportfInfo7;
    private javax.swing.JLabel sportfInfo8;
    private javax.swing.JLabel sportfInfo9;
    private javax.swing.JLabel sportfT;
    // End of variables declaration//GEN-END:variables
}
