/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZPontiac3 extends javax.swing.JFrame {

    /**
     * Creates new form ZPontiac
     */
    public ZPontiac3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        starchiefT = new javax.swing.JLabel();
        starchiefInfo1 = new javax.swing.JLabel();
        starchiefInfo2 = new javax.swing.JLabel();
        starchiefInfo3 = new javax.swing.JLabel();
        starchiefInfo4 = new javax.swing.JLabel();
        starchiefInfo5 = new javax.swing.JLabel();
        starchiefInfo6 = new javax.swing.JLabel();
        starchiefInfo7 = new javax.swing.JLabel();
        starchiefInfo8 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jtp_starchief = new javax.swing.JTabbedPane();
        starchief1 = new javax.swing.JLabel();
        starchief2 = new javax.swing.JLabel();
        starchief3 = new javax.swing.JLabel();
        backPontiac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pontiac 3/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        starchiefT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        starchiefT.setForeground(new java.awt.Color(255, 255, 255));
        starchiefT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starchiefT.setText("PONTIAC Star Chief");
        getContentPane().add(starchiefT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 320, 30));

        starchiefInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        starchiefInfo1.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(starchiefInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 320, 30));

        starchiefInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo2.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo2.setText("ANO FABRICAÇÃO: 1958"); // NOI18N
        getContentPane().add(starchiefInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 320, 30));

        starchiefInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo3.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo3.setText("QUILOMETRAGEM: 131.597"); // NOI18N
        getContentPane().add(starchiefInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 320, 30));

        starchiefInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo4.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo4.setText("MOTOR: V6 (3.8 litros)"); // NOI18N
        getContentPane().add(starchiefInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 320, 30));

        starchiefInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo5.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo5.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(starchiefInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 320, 30));

        starchiefInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo6.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo6.setText("CÂMBIO: Automático"); // NOI18N
        getContentPane().add(starchiefInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 320, 30));

        starchiefInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo7.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo7.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(starchiefInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 320, 30));

        starchiefInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        starchiefInfo8.setForeground(new java.awt.Color(255, 255, 255));
        starchiefInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        starchiefInfo8.setText("COR: Verde"); // NOI18N
        getContentPane().add(starchiefInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 320, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Anterior");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_starchief.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_starchief.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        starchief1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/star chief/Star1.png"))); // NOI18N
        jtp_starchief.addTab("1/3", starchief1);

        starchief2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/star chief/Star2.png"))); // NOI18N
        jtp_starchief.addTab("2/3", starchief2);

        starchief3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/star chief/Star3.png"))); // NOI18N
        jtp_starchief.addTab("3/3", starchief3);

        getContentPane().add(jtp_starchief, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 360, 220));

        backPontiac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backPontiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZPontiac3.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backPontiac;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_starchief;
    private javax.swing.JLabel starchief1;
    private javax.swing.JLabel starchief2;
    private javax.swing.JLabel starchief3;
    private javax.swing.JLabel starchiefInfo1;
    private javax.swing.JLabel starchiefInfo2;
    private javax.swing.JLabel starchiefInfo3;
    private javax.swing.JLabel starchiefInfo4;
    private javax.swing.JLabel starchiefInfo5;
    private javax.swing.JLabel starchiefInfo6;
    private javax.swing.JLabel starchiefInfo7;
    private javax.swing.JLabel starchiefInfo8;
    private javax.swing.JLabel starchiefT;
    // End of variables declaration//GEN-END:variables
}
