/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZPontiac extends javax.swing.JFrame {

    /**
     * Creates new form ZPontiac
     */
    public ZPontiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grandpixT = new javax.swing.JLabel();
        grandpixInfo1 = new javax.swing.JLabel();
        grandpixInfo2 = new javax.swing.JLabel();
        grandpixInfo3 = new javax.swing.JLabel();
        grandpixInfo4 = new javax.swing.JLabel();
        grandpixInfo5 = new javax.swing.JLabel();
        grandpixInfo6 = new javax.swing.JLabel();
        grandpixInfo7 = new javax.swing.JLabel();
        grandpixInfo8 = new javax.swing.JLabel();
        grandpixInfo9 = new javax.swing.JLabel();
        firebirdT = new javax.swing.JLabel();
        firebirdInfo1 = new javax.swing.JLabel();
        firebirdInfo2 = new javax.swing.JLabel();
        firebirdInfo3 = new javax.swing.JLabel();
        firebirdInfo4 = new javax.swing.JLabel();
        firebirdInfo5 = new javax.swing.JLabel();
        firebirdInfo6 = new javax.swing.JLabel();
        firebirdInfo7 = new javax.swing.JLabel();
        firebirdInfo8 = new javax.swing.JLabel();
        firebirdInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_proxima = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jtp_grandpix = new javax.swing.JTabbedPane();
        grandpix1 = new javax.swing.JLabel();
        grandpix2 = new javax.swing.JLabel();
        grandpix3 = new javax.swing.JLabel();
        grandpix4 = new javax.swing.JLabel();
        jtp_firebird = new javax.swing.JTabbedPane();
        firebird1 = new javax.swing.JLabel();
        firebird2 = new javax.swing.JLabel();
        firebird3 = new javax.swing.JLabel();
        backPontiac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pontiac 1/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grandpixT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        grandpixT.setForeground(new java.awt.Color(255, 255, 255));
        grandpixT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grandpixT.setText("PONTIAC Grand Prix");
        getContentPane().add(grandpixT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 30));

        grandpixInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        grandpixInfo1.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(grandpixInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 340, 30));

        grandpixInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo2.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo2.setText("ANO FABRICAÇÃO: 1966"); // NOI18N
        getContentPane().add(grandpixInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 340, 30));

        grandpixInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo3.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo3.setText("QUILOMETRAGEM: 152.887"); // NOI18N
        getContentPane().add(grandpixInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 340, 30));

        grandpixInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo4.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo4.setText("POTÊNCIA: 294 HP"); // NOI18N
        getContentPane().add(grandpixInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 340, 30));

        grandpixInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo5.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo5.setText("MOTOR: V8 (6.8 litros)"); // NOI18N
        getContentPane().add(grandpixInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 340, 30));

        grandpixInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo6.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo6.setText("CÂMBIO: Automático - 3 Velocidades "); // NOI18N
        getContentPane().add(grandpixInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 340, 30));

        grandpixInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo7.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo7.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(grandpixInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 340, 30));

        grandpixInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo8.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo8.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(grandpixInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 340, 30));

        grandpixInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        grandpixInfo9.setForeground(new java.awt.Color(255, 255, 255));
        grandpixInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grandpixInfo9.setText("COR: Bege"); // NOI18N
        getContentPane().add(grandpixInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 340, 30));

        firebirdT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        firebirdT.setForeground(new java.awt.Color(255, 255, 255));
        firebirdT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firebirdT.setText("PONTIAC Firebird TransAm");
        getContentPane().add(firebirdT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 260, 30));

        firebirdInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        firebirdInfo1.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(firebirdInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 340, 30));

        firebirdInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo2.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1979/1979"); // NOI18N
        getContentPane().add(firebirdInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 340, 30));

        firebirdInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo3.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo3.setText("COR: Preto - Starlight Black "); // NOI18N
        getContentPane().add(firebirdInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 340, 30));

        firebirdInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo4.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo4.setText("MOTOR: V8 (7.6 litros)"); // NOI18N
        getContentPane().add(firebirdInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 340, 30));

        firebirdInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo5.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo5.setText("POTÊNCIA: 235 CV "); // NOI18N
        getContentPane().add(firebirdInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 340, 30));

        firebirdInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo6.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo6.setText("CÂMBIO: Automático - 3 Velocidades "); // NOI18N
        getContentPane().add(firebirdInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 340, 30));

        firebirdInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo7.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo7.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(firebirdInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 340, 30));

        firebirdInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo8.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo8.setText("VELOCIDADE MÁXIMA: 216 Km/h "); // NOI18N
        getContentPane().add(firebirdInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 340, 30));

        firebirdInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        firebirdInfo9.setForeground(new java.awt.Color(255, 255, 255));
        firebirdInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firebirdInfo9.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(firebirdInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 340, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        jtp_grandpix.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_grandpix.setToolTipText("");
        jtp_grandpix.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        grandpix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/grand pix/Grand1.png"))); // NOI18N
        jtp_grandpix.addTab("1/4", grandpix1);

        grandpix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/grand pix/Grand2.png"))); // NOI18N
        jtp_grandpix.addTab("2/4", grandpix2);

        grandpix3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/grand pix/Grand3.png"))); // NOI18N
        jtp_grandpix.addTab("3/4", grandpix3);

        grandpix4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/grand pix/Grand4.png"))); // NOI18N
        jtp_grandpix.addTab("4/4", grandpix4);

        getContentPane().add(jtp_grandpix, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 230));

        jtp_firebird.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_firebird.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        firebird1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/firebird/Firebird1.png"))); // NOI18N
        jtp_firebird.addTab("1/3", firebird1);

        firebird2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/firebird/Firebird2.png"))); // NOI18N
        jtp_firebird.addTab("2/3", firebird2);

        firebird3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/firebird/Firebird3.png"))); // NOI18N
        jtp_firebird.addTab("3/3", firebird3);

        getContentPane().add(jtp_firebird, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 290, -1));

        backPontiac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backPontiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZPontiac2 p2 = new ZPontiac2();
        p2.setVisible(true);
        
    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZPontiac.this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backPontiac;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel firebird1;
    private javax.swing.JLabel firebird2;
    private javax.swing.JLabel firebird3;
    private javax.swing.JLabel firebirdInfo1;
    private javax.swing.JLabel firebirdInfo2;
    private javax.swing.JLabel firebirdInfo3;
    private javax.swing.JLabel firebirdInfo4;
    private javax.swing.JLabel firebirdInfo5;
    private javax.swing.JLabel firebirdInfo6;
    private javax.swing.JLabel firebirdInfo7;
    private javax.swing.JLabel firebirdInfo8;
    private javax.swing.JLabel firebirdInfo9;
    private javax.swing.JLabel firebirdT;
    private javax.swing.JLabel grandpix1;
    private javax.swing.JLabel grandpix2;
    private javax.swing.JLabel grandpix3;
    private javax.swing.JLabel grandpix4;
    private javax.swing.JLabel grandpixInfo1;
    private javax.swing.JLabel grandpixInfo2;
    private javax.swing.JLabel grandpixInfo3;
    private javax.swing.JLabel grandpixInfo4;
    private javax.swing.JLabel grandpixInfo5;
    private javax.swing.JLabel grandpixInfo6;
    private javax.swing.JLabel grandpixInfo7;
    private javax.swing.JLabel grandpixInfo8;
    private javax.swing.JLabel grandpixInfo9;
    private javax.swing.JLabel grandpixT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_firebird;
    private javax.swing.JTabbedPane jtp_grandpix;
    // End of variables declaration//GEN-END:variables
}
