/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author mythg
 */
public class ZPontiac2 extends javax.swing.JFrame {

    /**
     * Creates new form ZPontiac
     */
    public ZPontiac2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempestT = new javax.swing.JLabel();
        tempestInfo1 = new javax.swing.JLabel();
        tempestInfo2 = new javax.swing.JLabel();
        tempestInfo3 = new javax.swing.JLabel();
        tempestInfo4 = new javax.swing.JLabel();
        tempestInfo5 = new javax.swing.JLabel();
        tempestInfo6 = new javax.swing.JLabel();
        tempestInfo7 = new javax.swing.JLabel();
        tempestInfo8 = new javax.swing.JLabel();
        tempestInfo9 = new javax.swing.JLabel();
        gtoT = new javax.swing.JLabel();
        gtoInfo1 = new javax.swing.JLabel();
        gtoInfo2 = new javax.swing.JLabel();
        gtoInfo3 = new javax.swing.JLabel();
        gtoInfo4 = new javax.swing.JLabel();
        gtoInfo5 = new javax.swing.JLabel();
        gtoInfo6 = new javax.swing.JLabel();
        gtoInfo7 = new javax.swing.JLabel();
        gtoInfo8 = new javax.swing.JLabel();
        gtoInfo9 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_proxima = new javax.swing.JButton();
        jtp_tempest = new javax.swing.JTabbedPane();
        tempest1 = new javax.swing.JLabel();
        tempest2 = new javax.swing.JLabel();
        tempest3 = new javax.swing.JLabel();
        tempest4 = new javax.swing.JLabel();
        jtp_gto = new javax.swing.JTabbedPane();
        gto1 = new javax.swing.JLabel();
        gto2 = new javax.swing.JLabel();
        gto3 = new javax.swing.JLabel();
        gto4 = new javax.swing.JLabel();
        backPontiac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pontiac 2/3");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tempestT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        tempestT.setForeground(new java.awt.Color(255, 255, 255));
        tempestT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempestT.setText("PONTIAC Tempest Le Mans");
        getContentPane().add(tempestT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 360, 30));

        tempestInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        tempestInfo1.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(tempestInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 360, 30));

        tempestInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo2.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo2.setText("ANO FABRICAÇÃO: 1965"); // NOI18N
        getContentPane().add(tempestInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 360, 30));

        tempestInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo3.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo3.setText("QUILOMETRAGEM: 144.194"); // NOI18N
        getContentPane().add(tempestInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 360, 30));

        tempestInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo4.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo4.setText("MOTOR: V8 (5.3 litros)"); // NOI18N
        getContentPane().add(tempestInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 360, 30));

        tempestInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo5.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo5.setText("POTÊNCIA: 292 HP "); // NOI18N
        getContentPane().add(tempestInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 360, 30));

        tempestInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo6.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo6.setText("CÂMBIO: Automático"); // NOI18N
        getContentPane().add(tempestInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 360, 30));

        tempestInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo7.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo7.setText("COMBUSTÍVEL: Gasolina "); // NOI18N
        getContentPane().add(tempestInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 360, 30));

        tempestInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo8.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo8.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(tempestInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 360, 30));

        tempestInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        tempestInfo9.setForeground(new java.awt.Color(255, 255, 255));
        tempestInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tempestInfo9.setText("COR: Prata"); // NOI18N
        getContentPane().add(tempestInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 360, 30));

        gtoT.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        gtoT.setForeground(new java.awt.Color(255, 255, 255));
        gtoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gtoT.setText("PONTIAC GTO \"The Judge\"");
        getContentPane().add(gtoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 340, 30));

        gtoInfo1.setFont(new java.awt.Font("Myanmar Text", 3, 16)); // NOI18N
        gtoInfo1.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo1.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(gtoInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 340, 30));

        gtoInfo2.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo2.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo2.setText("ANO FABRICAÇÃO/ANO MODELO: 1968/1968 "); // NOI18N
        getContentPane().add(gtoInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 340, 30));

        gtoInfo3.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo3.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo3.setText("COR: Carousel Red "); // NOI18N
        getContentPane().add(gtoInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 340, 30));

        gtoInfo4.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo4.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo4.setText("QUILOMETRAGEM: 1.638 "); // NOI18N
        getContentPane().add(gtoInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 340, 30));

        gtoInfo5.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo5.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo5.setText("MOTOR: V8 (6.6 litros)"); // NOI18N
        getContentPane().add(gtoInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 340, 30));

        gtoInfo6.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo6.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo6.setText("POTÊNCIA: 371 CV "); // NOI18N
        getContentPane().add(gtoInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 340, 30));

        gtoInfo7.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo7.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo7.setText("CÂMBIO: Manual - 4 velocidades "); // NOI18N
        getContentPane().add(gtoInfo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 340, -1));

        gtoInfo8.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo8.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo8.setText("TRAÇÃO: Traseira "); // NOI18N
        getContentPane().add(gtoInfo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 340, 30));

        gtoInfo9.setFont(new java.awt.Font("Myanmar Text", 0, 16)); // NOI18N
        gtoInfo9.setForeground(new java.awt.Color(255, 255, 255));
        gtoInfo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gtoInfo9.setText("INFORMAÇÕES GERAIS"); // NOI18N
        getContentPane().add(gtoInfo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 340, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        btn_voltar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/anterior.png"))); // NOI18N
        btn_voltar.setText("Anterior");
        btn_voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, -1, 30));

        btn_proxima.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btn_proxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/proxima.png"))); // NOI18N
        btn_proxima.setText("Próxima");
        btn_proxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, -1, 30));

        jtp_tempest.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_tempest.setToolTipText("");
        jtp_tempest.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        tempest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/tempest/Tempest1.png"))); // NOI18N
        jtp_tempest.addTab("1/4", tempest1);

        tempest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/tempest/Tempest2.png"))); // NOI18N
        jtp_tempest.addTab("2/4", tempest2);

        tempest3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/tempest/Tempest3.png"))); // NOI18N
        jtp_tempest.addTab("3/4", tempest3);

        tempest4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/tempest/Tempest4.png"))); // NOI18N
        jtp_tempest.addTab("4/4", tempest4);

        getContentPane().add(jtp_tempest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 400, 250));

        jtp_gto.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jtp_gto.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        gto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/gto/Gto1.png"))); // NOI18N
        jtp_gto.addTab("1/4", gto1);

        gto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/gto/Gto2.png"))); // NOI18N
        jtp_gto.addTab("2/4", gto2);

        gto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/gto/Gto3.png"))); // NOI18N
        jtp_gto.addTab("3/4", gto3);

        gto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/carros/pontiac/gto/Gto4.png"))); // NOI18N
        jtp_gto.addTab("4/4", gto4);

        getContentPane().add(jtp_gto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 380, 220));

        backPontiac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.png"))); // NOI18N
        getContentPane().add(backPontiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximaActionPerformed

        ZPontiac3 p2 = new ZPontiac3();
        p2.setVisible(true);

    }//GEN-LAST:event_btn_proximaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        ZPontiac2.this.dispose();
        
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backPontiac;
    private javax.swing.JButton btn_proxima;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel gto1;
    private javax.swing.JLabel gto2;
    private javax.swing.JLabel gto3;
    private javax.swing.JLabel gto4;
    private javax.swing.JLabel gtoInfo1;
    private javax.swing.JLabel gtoInfo2;
    private javax.swing.JLabel gtoInfo3;
    private javax.swing.JLabel gtoInfo4;
    private javax.swing.JLabel gtoInfo5;
    private javax.swing.JLabel gtoInfo6;
    private javax.swing.JLabel gtoInfo7;
    private javax.swing.JLabel gtoInfo8;
    private javax.swing.JLabel gtoInfo9;
    private javax.swing.JLabel gtoT;
    private javax.swing.JLabel icon;
    private javax.swing.JTabbedPane jtp_gto;
    private javax.swing.JTabbedPane jtp_tempest;
    private javax.swing.JLabel tempest1;
    private javax.swing.JLabel tempest2;
    private javax.swing.JLabel tempest3;
    private javax.swing.JLabel tempest4;
    private javax.swing.JLabel tempestInfo1;
    private javax.swing.JLabel tempestInfo2;
    private javax.swing.JLabel tempestInfo3;
    private javax.swing.JLabel tempestInfo4;
    private javax.swing.JLabel tempestInfo5;
    private javax.swing.JLabel tempestInfo6;
    private javax.swing.JLabel tempestInfo7;
    private javax.swing.JLabel tempestInfo8;
    private javax.swing.JLabel tempestInfo9;
    private javax.swing.JLabel tempestT;
    // End of variables declaration//GEN-END:variables
}
